### PR TITLE
WIP: Add no-install param to poetry add

### PR DESCRIPTION
**Pull request by adisbladis**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://python-poetry.org/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by sdispater** [comment]
Since there is no feature request issue related to this: which use case does this try to solve?

I don't see the value of this feature and seems more like and edge but I might be wrong.

**Comment by adisbladis** [comment]
It is a bit of a "strange" use-case. I want to let poetry deal with dependency solving _only_ and let https://github.com/nix-community/poetry2nix create/load the environments.

**Comment by juhoautio** [comment]
I have a slightly different kind of use case for this feature. I have a project generator that wraps poetry to create a structure that extends poetry's defaults. For this I'm using `poetry new`, followed by `poetry add` to add some additional default dependencies. However, `poetry add` also creates the virtual environment and installs the dependencies, which takes some time.

On the other hand, the interactive `poetry init` allows specifying additional dependencies without installing them. But it's not ideal to wrap the interactive command when further input is not wanted by the user.

To explain the use case a bit more, workflow is that a user could run `mygenerator new` quickly, then edit the `pyproject.toml` manually to for example remove unwanted default dependencies, and run `poetry install` once done with the manual editing. Also, as `poetry init` & `poetry new` don't create the virtual environment, I would like my generator to be able to skip it.

My use case could be cleanly implemented with any of these changes in poetry:
- Add a `--no-install` option to `poetry add`
- Add options `--dependencies` and `--dev-dependencies` to `poetry new` (this is my favorite, because why not, when `init` already supports these flags)
- Add option `--no-interactive` to `poetry init`
- Add a function in poetry lib that allows easily modifying `pyproject.toml` so that it preserves the original layout of `poetry new`

**Comment by tbenst** [comment]
I found a workaround...if you ctrl-c at the right time, the appropriate lines are added to `pyproject.toml`, and you can subsequently do `poetry lock`! LOL no-install is better...

**Comment by adisbladis** [comment]
Poetry now has a `--lock` argument which seems to achieve the exact same thing I was aiming for.

**Pull request closed without merging**
