### PR TITLE
#1393 Add system site-packages support in virtualenv (again)

### PR DESCRIPTION
**Pull request by kam1sh**
# Pull Request Check List

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.
- [x] Fixed existing tests (on my machine)
- [x] Fixed existing tests (in CI)
- [x] Added logging for changed code

Looks like I really like Poetry, because I'm sumbitting this PR again (previous is #1404). But now I decided to rename setting from `virtualenvs.include-system-packages` to just `virtualenvs.system-packages`. I hope it could be merged now at least...

If you think there is a lack in something in this PR, just say and I'll do my best. I have enough spare time to dig in Poetry code base & tests =)

### CODE REVIEW

**Review by Conan-Kudo — DISMISSED** [review]

**Comment by four43** [comment]
This will be great for working with `conda` to install scientific packages, then using `poetry` to do the rest.

**Comment by etijskens** [comment]
Fully agree
Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 19 Feb 2020, at 01:19, Seth Miller <notifications@github.com<mailto:notifications@github.com>> wrote:


This will be great for working with conda to install scientific packages, then using poetry to do the rest.

**Comment by etijskens** [comment]
many thanks!

**Comment by abn** [comment]
Apoligies for dropping the ball on this one. Feel free to ping on discord if something falls through the crack again. We appricate your contributions, issues reports, PRs and doc fixes alike.

For this particular change, is it possible to get this rebased against `master` and aligned with what has been merged in #3157 using the `virtualenvs.options` namespace?

**Comment by etijskens** [comment]
can anybody tell me the status of this feature?
I would like to use poetry on a supercomputer, where not using system site packages is an absolute no go. The system site packages are compiled with special care for performances issues.

**Comment by sinoroc** [comment]
> I would like to use poetry on a supercomputer, where not using system site packages is an absolute no go. The system site packages are compiled with special care for performances issues.

A different approach to this:
Why not package those custom-compiled dependencies as wheels and distribute them via a custom index repository?

**Comment by vlad0337187** [comment]
@abn, fixed this in [PR](https://github.com/python-poetry/poetry/pull/3711), could you review please ?

**Comment by ClementWalter** [comment]
is this released yet? Would really appreciate to use the feature

**Comment by vlad0337187** [comment]
@ClementWalter , no it wasn't released yet.
But you can install it from GitHub directly:
 `pipx install git+https://github.com/python-poetry/poetry.git`

**Pull request closed without merging**
