### PR TITLE
Support `Private ::` trove classifiers

### PR DESCRIPTION
**Pull request by johnthagen**
# Pull Request Check List

Resolves: #7167

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by johnthagen** [comment]
I could use the help from a Poetry dev to help debug the failing test I added. I tried to model it off the existing tests, but something is not working correctly.

https://github.com/python-poetry/poetry/actions/runs/3812843426/jobs/6486267099#step:14:1757

**Comment by radoering** [comment]
`fetch_error` vs. `fetch_output`?

**Comment by johnthagen** [comment]
> fetch_error vs. fetch_output?

🤦‍♂️ That would do it. Thanks!

**Comment by johnthagen** [comment]
If this PR is accepted, please squash the commits using GitHub's commit UI. Thanks.

**Review by Secrus — APPROVED** [review]

**Comment by johnthagen** [comment]
The CI failure looks spurious?

**Comment by johnthagen** [comment]
@Secrus Anything else need to be done for this PR to be merged? Thanks.

**Review by Secrus — APPROVED** [review]

**Pull request merged**
