### PR TITLE
Experimental beeware based cross-platform build

### PR DESCRIPTION
**Pull request by abn**

### CODE REVIEW

**Comment by abn** [comment]
This might need some creative ways to handle virtual env management on target platform. For example, appimages on linux (since they mount host dirs) have some issues with links and detecting python versions available etc.

```console
$ ls -all .venv/bin/
total 80
drwxrwxr-x. 2 abn abn  500 Aug 23 20:54 .
drwxrwxr-x. 4 abn abn  120 Aug 23 20:54 ..
-rw-rw-r--. 1 abn abn 2206 Aug 23 20:54 activate
-rw-rw-r--. 1 abn abn 1425 Aug 23 20:54 activate.csh
-rw-rw-r--. 1 abn abn 3056 Aug 23 20:54 activate.fish
-rw-rw-r--. 1 abn abn 1751 Aug 23 20:54 activate.ps1
-rw-rw-r--. 1 abn abn 1199 Aug 23 20:54 activate_this.py
-rw-rw-r--. 1 abn abn 1147 Aug 23 20:54 activate.xsh
-rwxrwxr-x. 1 abn abn  242 Aug 23 20:54 easy_install
-rwxrwxr-x. 1 abn abn  242 Aug 23 20:54 easy_install3
-rwxrwxr-x. 1 abn abn  242 Aug 23 20:54 easy_install-3.8
-rwxrwxr-x. 1 abn abn  242 Aug 23 20:54 easy_install3.8
-rwxrwxr-x. 1 abn abn  233 Aug 23 20:54 pip
-rwxrwxr-x. 1 abn abn  233 Aug 23 20:54 pip3
-rwxrwxr-x. 1 abn abn  233 Aug 23 20:54 pip-3.8
-rwxrwxr-x. 1 abn abn  233 Aug 23 20:54 pip3.8
-rwxrwxr-x. 1 abn abn  217 Aug 23 20:54 py.test
-rwxrwxr-x. 1 abn abn  217 Aug 23 20:54 pytest
lrwxrwxrwx. 1 abn abn   40 Aug 23 20:54 python -> /tmp/.mount_poetryJN0vYe/usr/bin/python3
lrwxrwxrwx. 1 abn abn    6 Aug 23 20:54 python3 -> python
lrwxrwxrwx. 1 abn abn    6 Aug 23 20:54 python3.8 -> python
-rwxrwxr-x. 1 abn abn  220 Aug 23 20:54 wheel
-rwxrwxr-x. 1 abn abn  220 Aug 23 20:54 wheel3
-rwxrwxr-x. 1 abn abn  220 Aug 23 20:54 wheel-3.8
-rwxrwxr-x. 1 abn abn  220 Aug 23 20:54 wheel3.8
$ rm -rf .venv/
$ /tmp/poetry/linux/poetry-1.1.0b2-x86_64.AppImage env use 3.7

  NoCompatiblePythonVersionFound

  The specified Python version (3.7.8) is not supported by the project (^3.8).
  Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.

  at /tmp/.mount_poetryXWv0xx/usr/app/poetry/utils/env.py:558 in create_venv
       554│             # If an executable has been specified, we stop there
       555│             # and notify the user of the incompatibility.
       556│             # Otherwise, we try to find a compatible Python version.
       557│             if executable:
    →  558│                 raise NoCompatiblePythonVersionFound(
       559│                     self._poetry.package.python_versions, python_patch
       560│                 )
       561│ 
       562│             io.write_line(
$ 
```

**Comment by abn** [comment]
The current AppImage build does not accelt cli-args. This will be resolved once https://github.com/beeware/briefcase-linux-appimage-template/pull/3 is merged.

**Comment by neersighted** [comment]
Hey @abn, is this still relevant in light of `install-poetry.py`?

**Comment by abn** [comment]
Good question. I think it still is. Installer script still is not a consistent experience for users. Neither is update experience. The intent for this was to see if we can distribute poetry better. As an added benefit this process did highlight a few not so great assumptions we make in the code today. 

That said the pr is a bit stale and I think I need to go back to the drawing board a bit. So we can maybe close this for now till there is a better option.

**Pull request closed without merging**
