### PR TITLE
Add PyPI registry correctly to pool depending on other sources/Fix source.secondary = true being ignored

### LINKED ISSUE #2339: Poetry not respecting order of evaluation for repository sources
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Mac OS 10.15.3
- **Poetry version**: 1.0.5

## Issue
So, I am trying to configure a pyproject.toml file that supports pulling files from pypi.org whenever possible (ie: because on my site the performance is better) but will support pulling packages that aren't found on pypi.org from a secondary location (ie: a private pypi repo). So to start with I added a section like what follows to a sample toml file for testing:

```
[[tool.poetry.source]]
name = 'default'
url = 'https://pypi.python.org/simple'
default = true

[[tool.poetry.source]]
name = "private"
url = "https://private/server/url
secondary = true

[tool.poetry.dependencies]
python = "^3.6"
sphinx = "*"
```

Based on the docs, I was under the impression that by putting `default=true` on the first repo config, and `secondary=true` on the other one, that my goal would be achieved: if a package exists on pypi.org it'd pull it from there and if not it'd pull it from my secondary repo. However, that does not seem to be the case.

For the sake of this discussion I am using average performance metrics from running `poetry lock` on this toml file and comparing the length of time it takes to resolve the dependencies of the one Python package mentioned (ie: `sphinx` which is a standard Python package available on pypi.org). 

So, running `poetry lock` on this file using the configuration I posted above takes about 20-25 seconds to complete. For comparison purposes I simply removed the second source definition from the toml file giving me:

```
[[tool.poetry.source]]
name = 'default'
url = 'https://pypi.python.org/simple'
default = true

[tool.poetry.dependencies]
python = "^3.6"
sphinx = "*"
```

Re-running the same common against this toml file takes between 2 and 3 seconds to complete - a full order of magnitude difference in performance. Now, for my 3rd and final test I removed the first repo source leaving just the second one, giving me the following configuration block:

```
[[tool.poetry.source]]
name = "private"
url = "https://private/server/url
secondary = true

[tool.poetry.dependencies]
python = "^3.6"
sphinx = "*"
```

Re-running the same command again takes about the same 20-25 seconds to complete (NOTE: our private pypi repository is also a mirror of the public pypi.org repo so I can compare the same package versions and resolution times in all cases).

So, based on these results, the only explanation I can see is that when the second repository definition is in place the public pypi.org repo is being ignored or something and the secondary / private repo is still being accessed for some reason.

My expectation here is that poetry would iterate over the various repos defined in the toml file in order of declaration. For each package listed in the toml file it should then try to access / index each package against each repository stopping when it finds the first match. If this were true then I would have expected my first test case above to perform identically to the second one because the package I'm testing (sphinx) should exist on pypi.org, and all of it's transitive dependencies will be available there as well. However this is obviously not the case.

So my question is - is this a bug or is there some additional configuration options I need to specify to get this to work as I was expecting?

### LINKED ISSUE #3238: Custom repository doesn't have precedence over PyPI
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave 10.14.6
- **Poetry version**: 1.1.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
```toml
[[tool.poetry.source]]
name = 'foobar'
url = 'http://repository.intranet.foobar.com/artifactory/api/pypi/pypi-virtual/simple'

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue
In docs we can read:
> Any custom repository will have precedence over PyPI.

In the above example, `foobar` is a proxy repo incl. both internal packages and the public ones from PyPI. Running `poetry install` should cause a creation of `poetry.lock`, where all the packages have `foobar` in their `source` field. However, it's completely opposite - none of the packages has a `source` field, which means all of them are downloaded directly from PyPI.

When I add `default = true` to the above `source` element, which means PyPI is disabled, everything works properly - generated `poetry.lock` includes `foobar` as a `source` for all packages and installation doesn't break, so it's not a problem with repository itself.

It's especially frustrating when you want to use `poetry export` (for any reason), because then the final `requirements.txt` doesn't include neither `--index-url` nor `--extra-index-url` (it seems it depends on the actually used sources, not the `pyproject.toml` content).

### LINKED ISSUE #3306: poetry 1.1.4 locks all packages to be pulled from secondary repo
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14
- **Poetry version**: 1.1.4

## Issue

Hi,

I'm experiencing this behavior on 1.1.4. In `pyproject.toml` I have configured a secondary repo:

```toml
[[tool.poetry.source]]
name = "xxx"
url = "https://PRIVATE"
secondary = true
```

As such, I expect that `poetry` will fetch most packages from the main PyPI. And 1.1.3 indeed does that. However, 1.1.4 adds this configuration to every package (non-private as well) in `poetry.lock`:

```toml
[[package]]
name = "alabaster"
version = "0.7.12"
description = "A configurable sidebar-enabled Sphinx theme"
category = "main"
optional = true
python-versions = "*"

[package.source]
type = "legacy"
url = "https://PRIVATE"
reference = "xxx"
```

IMO this is unexpected behavior. I did `git bisect` and found out that this bug was introduced in 74fc8eb1cafe2006c22a969d5c0cd53968e46f2a, in an attempt to fix other pypi-related issues.

### PR DESCRIPTION
**Pull request by tomzx**
In the event where we defined sources that were set as
secondary = True, we would end up with PyPI being after this source
when it should have acted as default in that case.

The main issue stems from the fact that it's not because you have
sources configured that PyPI should not be a default. Instead, PyPI
should be default if there are no sources with secondary = False and
not default if there are sources with secondary = True.

Resolves #2339, resolves #3306, resolves #3238

### CODE REVIEW

**Review by aviramha — DISMISSED** [review]
Great job!

**Comment by maksbotan** [comment]
I can confirm it works, thanks! Looking forward for a release.

**Comment by aviramha** [comment]
@abn any chance to merge this? This is quite an issue for us.

**Comment by dbuades** [comment]
Same thing here, we found this error today in different computers. It would be great if this could be merged!

**Comment by michaeljoy** [comment]
Still an issue, when will this make it into master?

**Comment by skylerwshaw** [comment]
@tomzx @aviramha When can we expect a merge and release? Thanks!

**Comment by tomzx** [comment]
@skylerwshaw I cannot merge this since I am not a maintainer. Merging is currently blocked due to
> At least 1 approving review is required by reviewers with write access.

**Review by Drachenfels — APPROVED** [review]

**Comment by pPanda-beta** [comment]
"A stitch in time saves nine" - should have merged already. People are suffering out there because of the secondary repositories.

**Comment by ylathouris** [comment]
Is there a workaround for this issue?

**Review by ylathouris — APPROVED** [review]

**Comment by tomzx** [comment]
Hello all! I have rebased the PR which appears to have rendered the 3 prior approval stale.

@Drachenfels @ylathouris @aviramha Would you mind giving it another quick look (nothing has changed).

@sdispater @abn Would you be able to provide any feedback necessary to get this moving forward?

Thanks!

**Review by aviramha — DISMISSED** [review]

**Comment by chalupaul** [comment]
bueller.... bueller.... bueller.......

**Comment by GooseYArd** [comment]
I think this project is dead. Nearly 200 pending PRs, 800+ open issues, a handful of commits in the last three months.

**Comment by maksbotan** [comment]
@sdispater @abn @cereblanco hi! glad to see the project come to life again. Can you please look at this PR, as it fixes a nasty regression that blocks some users from upgrading to 1.1.4?

**Comment by FraBle** [comment]
> Conflicting files
> poetry/factory.py

😭

**Comment by tomzx** [comment]
> > Conflicting files
> > poetry/factory.py

That's resolved.

**Comment by maksbotan** [comment]
@abn hi! this serious regression still did not get any attention from the developers...

**Review by sdispater — APPROVED** [review]
Looks good to me 👍

**Comment by caniko** [comment]
This didn't solve the problem for me.

**Comment by jstriebel** [comment]
Just noticed that this PR was merged to the `master` branch which is used for the `1.2` development, while the current `1.1.x` releases are from the `1.1` branch. Since this fix would be quite useful, I added PR #4241 for the `1.1` branch, hoping to have this in a patch-release soon.

**Pull request merged**
