### PR TITLE
Suggest Tox isolated_build w/o poetry install

### PR DESCRIPTION
**Pull request by bittner**
Adapts the suggestion about how to integration Poetry with Tox (roughly) following @sinoroc's suggestion. The new way avoids a common anti-pattern (or better: outdated approach) in CI, the imperative installation of prerequisites.

Resolves: #1941

### CODE REVIEW

**Comment by igor47** [comment]
as [commented](https://github.com/python-poetry/poetry/issues/1941#issuecomment-631562961) on #1941 , i'm not sure this is the right approach. the currently-documented suggestion allows me to test my application with identical dependencies between local dev, CI, and production. i'm not sure how to do this otherwise

**Comment by bittner** [comment]
@igor47 Sure, this might work for you this way. But there should be _a better way_ to achieve just that. For you and for everyone else.

In a Tox configuration you should specify the dependencies in a _declarative_ way (that's what `deps =` is for). Then, any deployment strategy Tox supports can install just those dependencies. In other words, _Tox_ can choose which application or procedure it applies to ensure that those dependencies are installed.

By suggesting a `foobar install` command we're giving up on that clean separation of concerns, and on the flexibility we gain with that. That's bad. And we should make sure people apply the better strategy. Hence this change.

**Comment by Secrus** [comment]
Hi, @bittner are you still interested in contributing this to Poetry? If so, please describe both options as according to the team, both have their use.

**Comment by bittner** [comment]
> Hi, @bittner are you still interested in contributing this to Poetry? If so, please describe both options as according to the team, both have their use.

I'm not sure I understand. Do you intend, keep the current description and suggest my change only as an alternative way in the docs?

**Comment by Secrus** [comment]
> I'm not sure I understand. Do you intend, keep the current description and suggest my change only as an alternative way in the docs?

Yes, that would be the plan.

**Comment by finswimmer** [comment]
`tox` can be configured in multiple ways. It depends on what should be the code under test and which dependencies should be installed. The docs should include the several use cases.

1.
```
[tox]
isolated_build = true

[testenv]
deps =
    pytest
commands =
    pytest tests/ --import-mode importlib
```

`tox` will create an `sdist` package of the project and uses `pip` to install it in a fresh environment. Thus dependencies are resolved by `pip`.

2.
```
[tox]
isolated_build = true

[testenv]
whitelist_externals = poetry
commands_pre =
    poetry install --no-root --sync
commands =
    poetry run pytest tests/ --import-mode importlib
```

`tox` will create an `sdist` package of the project and uses `pip` to install it in a fresh environment. Thus dependencies are resolved by `pip` in the first place. But afterwards we run Poetry, which will install the locked dependencies into the environment.

3.
```
[tox]
isolated_build = true

[testenv]
skip_install = true
whitelist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run pytest tests/ --import-mode importlib
```

`tox` will not do any install. Poetry installs all the dependencies and the current package an editable mode. Thus tests are running against the local files and not the builded and installed package.

**Comment by bittner** [comment]
That's all good.

Just to avoid misunderstandings, my point is not what you _can_ do, but what you _should_ do.

Usually, the tool dictates how you should do things. I believe, you should tell Tox what to do and it will do it for you (i.e. no need to write down the installation command with your dependencies; only compile a list of dependencies). If you go against the design of the tool you interfere with some of its features and make changes of the setup more difficult.

As an alternative, if you want to run just sequences of actual commands then write a Makefile or a shell script.

As Poetry is a very popular tool, we have the responsibility to tell developers how to do things the right way. Hence this PR.

**Comment by finswimmer** [comment]
Hey @bittner,

the problem with "telling developers how to do things the right way" here, is that there is not a single way. It depends on the goal.

Your suggested changes describes the  way how to use tox in the same way, a lot of people are doing it, when developing a package with setuptools.

The current description, describes a way how to use locked dependencies. That's something a lot of poetry user wanted to do.

That's why I think it would be a great benefit for the docs to explain the different options and when to use what.

fin swimmer

**Comment by finswimmer** [comment]
Superseded by https://github.com/python-poetry/poetry/pull/6026

**Pull request closed without merging**
