### PR TITLE
Add examples for 'poetry add' with a version constraint (#1440)

### PR DESCRIPTION
**Pull request by bitswamp**
This addresses the documentation aspect of #1440.

It's a documentation-only change which affects the main readme and the output of `poetry help add`. 

These are the places I looked first for this info, but if there are other suitable spots to change, or if a different constraint format is preferred, let me know.

Thanks for your time!

### CODE REVIEW

**Comment by viq** [comment]
It would be appreciated for this to get in, as apparently people repeatedly stumble on this issue.

**Comment by finswimmer** [comment]
Hello @bitswamp ,

thanks a lot for helping to improve the documentation!

At least in my tests, it is not necessary to begin the version constraint with a `=`. Just use the sign you need.

Do you agree with this?

fin swimmer

**Comment by viq** [comment]
I disagree with this, 'package<5.0' doesn't work, you need to use
'package=<5.0' to get that constraint.

**Comment by finswimmer** [comment]
Hello again,

can you address what "doesn't work"?

My testing:

```
[tool.poetry]
name = "my_project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

```
$ poetry install
Creating virtualenv my-project in /home/finswimmer/1440/.venv
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

No dependencies to install or update

$ poetry add requests\<2.19.0

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file


Package operations: 5 installs, 0 updates, 0 removals

  - Installing certifi (2019.11.28)
  - Installing chardet (3.0.4)
  - Installing idna (2.6)
  - Installing urllib3 (1.22)
  - Installing requests (2.18.4)

$ poetry add "requests<2.18.0"

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file


Package operations: 0 installs, 3 updates, 0 removals

  - Updating idna (2.6 -> 2.5)
  - Updating urllib3 (1.22 -> 1.21.1)
  - Updating requests (2.18.4 -> 2.17.3)
```

Works without the `=`. The important thing when using `<` is to escape this sign by `\` or put the whole string within `"`. Because within a shell the `<` have a special meaning. The same for the `>`. I think it would be a good idea to give a note about this in the docs, because this might not be obvious to all people.

**Comment by bitswamp** [comment]
I see in the 1.0.0 announcement another format was presented using @ instead of =. It's in the docs now at https://python-poetry.org/docs/cli/#add. 

I'll update this PR to remove the readme change and add the same text from the docs to the output of `poetry help add`.

**Pull request closed without merging**
