### PR TITLE
Add docs and schema for multiple readme files support

### PR DESCRIPTION
**Pull request by wagnerluis1982**
- Add documentation for code at python-poetry/poetry-core#248
- Update `poetry-schema.json` to match core's version

# Pull Request Check List

Related to #873

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Review by neersighted — CHANGES_REQUESTED** [review]
This doc change is relatively meaningless without the core changes to go with it -- by that, I mean that even after your changes are merged into core, they will not be reflected.

Between alpha releases, poetry `master` normally tracks poetry-core. I would suggest waiting until your PR lands in core, and then updating `pyproject.toml` to reflect the Git dependency so that your changes can be used.

**Comment by wagnerluis1982** [comment]
@neersighted, please remember to also merge this, given core changes at python-poetry/poetry-core#248 is merged 😊

**Comment by neersighted** [comment]
I'm aware! I'm not sure of merging this yet because of two things -- the schema in this repo is actually useless, so I'm thinking we merge a PR to drop it and drop that change from this PR.

Additionally, the docs in `master` will be out of sync with the poetry-core dep -- still debating whether we add a git dep or just wait to merge this until after a poetry-core release. I'm not an expert there so I'll have to pick some other brains.

**Comment by Secrus** [comment]
@neersighted did anything change in the mean time or is it still undecided?

**Comment by neersighted** [comment]
> @neersighted did anything change in the meantime or is it still undecided?

We've had a core release since then, so we should be good to just drop the schema in this PR, and update the docs to reflect the current reality.

**Comment by neersighted** [comment]
This has been superseded by #5678 and #5158. Thank you for your contribution!

**Pull request closed without merging**
