### PR TITLE
docs: list `--why` as a suboption of `--tree` in `poetry show`

### PR DESCRIPTION
**Pull request by kosmv**
Hi!
Here's my attempt for #5625

### CODE REVIEW

**Comment by tgolsson** [comment]
See my comment on original issue; the docs are unclear but this is even less correct. :-)

**Comment by Secrus** [comment]
@kosmv thank you for your contribution. 

@tgolsson Can you please assist with clearing up how this should work? its cool feature, but in my testing it was hard to find how it should be used. Thank you in advance.

**Comment by kosmv** [comment]
@tgolsson Oh right, my bad. I didn't understand why `--why` can be used alone.

**Comment by tgolsson** [comment]
@Secrus Unless @kosmv wants to finish this I'll make a PR tonight :-) 

The intended behavior is as follows:

* You can use --why when showing table or when showing a tree for a single package.
* If you use --why for the table it'll include a `from a, b, c` column
* If you use --why for a single-package tree it'll root the tree at the parent packages instead of the queried package.

This comment contains the expected two use-cases: https://github.com/python-poetry/poetry/pull/5444#issuecomment-1098263805.

 The CLI command line is just utterly wrong; I think I had some rebase problems and didn't double-check that well enough. The docs one should probably just specify where it's applicable and not just "when applicable".

**Comment by kosmv** [comment]
@tgolsson Sorry for not reading your original pull request properly. 
My terminal width was reduced, so I couldn't see the `from package-name` column when I tried your feature.

I won't finish this, you can make your PR :)

**Pull request closed without merging**
