### PR TITLE
fix: workaround unsupported metadata version 2.4 in pkginfo

### PR DESCRIPTION
**Pull request by finswimmer**
`pkginfo` will show a warning if it detects metadata version:

```
NewMetadataVersion: New metadata version (2.4) higher than latest supported version: parsing as 2.3
  warnings.warn(NewMetadataVersion(self.metadata_version))
```

I decided to not suppress this message.

Related to https://github.com/python-poetry/poetry/issues/9670#issuecomment-2510587030

### CODE REVIEW

**Review by radoering — APPROVED** [review]

**Review by MichaReiser — COMMENTED** [review]
This fix might no longer be required. A new `pkginfo` version was released just a few minutes ago that adds support for 2.4.

What would be nice in general is if poetry wouldn't fail when seeing a newer minor version and instead just warns about it.

**Comment by dimbleby** [comment]
>  poetry wouldn't fail when seeing a newer minor version and instead just warns about it.

that already is the behaviour, since pkginfo 1.11.0

**Comment by radoering** [comment]
> This fix might no longer be required. A new pkginfo version was released just a few minutes ago that adds support for 2.4.

Thanks for the info.

> What would be nice in general is if poetry wouldn't fail when seeing a newer minor version and instead just warns about it.

Poetry did not fail before #9203. However, this resulted in #9195, which is worse than failing. It seems like `pkginfo` handles unknown METADATA versions better now so maybe we can (partially) revert #9203.

**Comment by dimbleby** [comment]
poetry only fails on unexpected metadata versions in some of the code paths, which I think adds to the general confusion (including my own)

eg so far as I can see the `_get_info_from_metadata()` path does not care about metadata version.

Probably this is why some people saw a problem and some did not - they either were or were not using pypi / a private repository.

**Comment by broodjeaap** [comment]
For anyone looking for a quick fix, you can downgrade poetry with:
`poetry self update 1.8.2`

**Comment by dimbleby** [comment]
it's upgrading pkginfo that helps, not downgrading poetry

**Comment by Buedenbender** [comment]
In my case it was resolved by 
```bash
pip install --upgrade pkginfo
pip install --upgrade poetry
pip install --upgrade pip
```

Aftwards i was able to successfully install ruff in my poetry env via
`poetry add -G dev ruff`

**Pull request merged**
