### PR TITLE
resume download by appending to existing file

### PR DESCRIPTION
**Pull request by CTimmerman**
# Pull Request Check List

Resolves: #3453 

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

I don't know how to test or document this here, but i've done so at https://gist.github.com/CTimmerman/ccf884f8c8dcc284588f1811ed99be6c and that worked fine.

### CODE REVIEW

**Comment by neersighted** [comment]
I'm not sure how to feel about this overall -- it adds another layer of complexity and potential frustration (see: transient PyPI connection issues/poisoned caches). 

If this was better abstracted/less brittle-looking, and had robust tests, I think it might have a shot. The present design just seems like another layer of potential network breakage, so I'm going to close this for now but remain open to a revised design.

**Comment by CTimmerman** [comment]
Whoa, excuse me for not having fixed this last Sunday. It's intentionally simple but maybe i can find and adapt an existing poetry test next week.

**Comment by CTimmerman** [comment]
Then again, i'll just use my own resume script or wget and pip as those are already available, without adding poetry as additional complexity.

**Comment by neersighted** [comment]
> 
> 
> Whoa, excuse me for not having fixed this last Sunday. It's intentionally simple but maybe i can find and adapt an existing poetry test next week.

I don't mean to try to turn you off contributing at all -- the PR was merely a year old with merge conflicts and unlikely to make it in the present state. If you feel you can make the change robust and testable, please do feel free to submit the change.

**Pull request closed without merging**
