### PR TITLE
Run pyupgrade with py36-plus flag

### PR DESCRIPTION
**Pull request by HarryPeach**
I noticed that #3861 ran a pyupgrade sweep on the codebase to remove some old code but still had some remaining fluff like ```from __future__ import unicode_literals``` which shouldn't be needed >3.0.

I ran the same tool with the `--py36-plus` flag, which should make some more edits. Let me know if any further changes are needed!

Relates-to: #3860

# Pull Request Check List

Resolves: N/A

- [ N/A ] Added **tests** for changed code.
- [ N/A ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by abn** [comment]
Looks like this change is equivalent to #3988 (minus pre-commit).

**Comment by kamyar** [comment]
Have completely missed this PR by 2 hours 🤦 , @abn how do you suggest we proceed?

**Comment by abn** [comment]
@kamyar considering #3988 is more complete, I am inclined to use that. Maybe add @HarryPeach as a co-author of the formatting changes commit?

**Comment by kamyar** [comment]
@abn great suggestion, just amended my commits in #3988  to also include @HarryPeach  :) 
Can you take a look if it look good or something else is also needed?

**Comment by neersighted** [comment]
I'm closing this in favor of #4758 as it uses the current pre-commit structure, skips files that should not be altered by pyupgrade (`get-poetry.py` and `install-poetry.py`), and because there have been enough changes to master that a new run is needed.

Thank you for the work on these PRs! I've incorporated the changes from review into my version, and given credit where due. Please submit more PRs cleaning out old code/cruft when you can!

**Pull request closed without merging**
