### PR TITLE
[Repositories] consider "data-requires-python" anchor in the link when finding packages

### PR DESCRIPTION
**Pull request by zbw0046**
## Pull Request Check List

Resolves: #2588

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

## Description
According to [PEP 503](https://www.python.org/dev/peps/pep-0503/), a repository MAY include a `data-requires-python` attribute on a file link. This exposes the `Requires-Python` metadata field, specified in `PEP 345`, for the corresponding release. Where this is present, installer tools SHOULD ignore the download when installing to a Python version that doesn't satisfy the requirement. 

However, in current logic `data-requires-python` in link is not considered in the `_get_release_info` method of `legacyRepository` class, which is the root cause of the #2588 .

This PR adds the checking of `data-requires-python` attribute. If it exists, we set `requires_python` in `release_info` as it says.

### CODE REVIEW

**Comment by zbw0046** [comment]
An example of the link: <a href="/tos/pkg/pypi/scikit-learn/scikit-learn-0.23.1.tar.gz#sha256=e3fec1c8831f8f93ad85581ca29ca1bb88e2da377fb097cf8322aa89c21bc9b8" data-requires-python=">=3.6">scikit-learn-0.23.1.tar.gz</a>

**Comment by dimbleby** [comment]
Per https://github.com/python-poetry/poetry/issues/2588#issuecomment-1172769456, poetry seems to get the right answer today - though I'm not sure that it's through the mechanism that this MR proposes.

If you are still interested in contributing this: the code has moved on quite a bit and so it'll need a rebase.  Also tests would be good...

**Comment by neersighted** [comment]
Thanks for the PR! This is now implemented in Poetry 1.2.

**Comment by neersighted** [comment]
Ah, shoot, I realized that I misread the PR on mobile -- I thought this was for yanked releases. This could potentially let Poetry do less work if we could rule out dists before downloading them. As such, I'm going to re-open it to discuss, even if it would need a lot of cleanup for merge into current Poetry.

**Pull request closed without merging**
