### PR TITLE
Allow fish commands to work in fish

### PR DESCRIPTION
**Pull request by max-sixty**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://python-poetry.org/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Updated **documentation** for changed code.

The existing code:
```
poetry completions fish > $(brew --prefix)/share/fish/vendor_completions.d/poetry.fish                                                           
fish: Invalid redirection target:
poetry completions fish > $(brew --prefix)/share/fish/vendor_completions.d/poetry.fish
                        ^
```

Resolves: #2278
Closes: #2307

### CODE REVIEW

**Comment by max-sixty** [comment]
@abn done!

**Comment by abn** [comment]
@max-sixty would be great if you can fix this in the doc too. Sorry missed that on my first pass.

**Comment by max-sixty** [comment]
Done @abn 

Also, FWIW, while I don't know fish that well, it looks like the completions are stored differently to my other tools; which are all stored with symbolic links:

```fish
 I  ⎈ test  /u/l/s/f/vendor_completions.d  pwd                                                                                                                                       Mon Apr 13 21:36:03 2020
/usr/local/share/fish/vendor_completions.d
 I  ⎈ test  /u/l/s/f/vendor_completions.d  ll                                                                                                                                        Mon Apr 13 21:36:45 2020
lrwxr-xr-x  69 maximilian 12 Apr  1:53 bat.fish -> ../../../Cellar/bat/0.13.0_1/share/fish/vendor_completions.d/bat.fish
lrwxr-xr-x  44 maximilian 17 Jun  2019 brew.fish -> ../../../Homebrew/completions/fish/brew.fish
lrwxr-xr-x  64 maximilian 25 Mar  1:23 fd.fish -> ../../../Cellar/fd/7.5.0/share/fish/vendor_completions.d/fd.fish
lrwxr-xr-x  67 maximilian  7 Mar  0:26 hub.fish -> ../../../Cellar/hub/2.14.2/share/fish/vendor_completions.d/hub.fish
.rw-r--r-- 10k maximilian 13 Apr 21:34 poetry.fish
lrwxr-xr-x  70 maximilian  3 Apr  1:01 rg.fish -> ../../../Cellar/ripgrep/12.0.1/share/fish/vendor_completions.d/rg.fish
```

**Comment by abn** [comment]
@max-sixty that should be file, it seems to be just the way brew installs those :)

**Pull request merged**
