### PR TITLE
fix bug no package name on installed repository

### PR DESCRIPTION
**Pull request by uelei**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://python-poetry.org/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by finswimmer** [comment]
Hello @uelei,

thanks a lot for your contribution!

What issue is your PR trying to solve? If an issue ticket exists please link to it, if not please create one for better documentation.

fin swimmer

**Comment by uelei** [comment]
I Commented on https://github.com/python-poetry/poetry/issues/1953

**Comment by zdog234** [comment]
I'm so tempted to install directly from your branch. This issue is such a pain

**Comment by abn** [comment]
@uelei can you verify if the issue happens for you with poetry@develop?

**Comment by glennmatthews** [comment]
The issue described in #1953 is still reproducible with poetry 1.1.0a2:

```
# poetry install
Skipping virtualenv creation, as specified in config file.

  TypeError

  expected string or bytes-like object

  at /usr/local/lib/python3.7/site-packages/poetry/core/utils/helpers.py:24 in canonicalize_name
       20│ _canonicalize_regex = re.compile("[-_]+")
       21│ 
       22│ 
       23│ def canonicalize_name(name):  # type: (str) -> str
    →  24│     return _canonicalize_regex.sub("-", name).lower()
       25│ 
       26│ 
       27│ def module_name(name):  # type: (str) -> str
       28│     return canonicalize_name(name).replace(".", "_").replace("-", "_")
```

I can confirm that the issue is no longer seen after this change:

```
# poetry install
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

No dependencies to install or update

  - Installing mypackage (0.1.0)
#
```

**Comment by AlexanderWillner** [comment]
Actually running in the same issue with `poetry==1.1.6` and `virtualenv==20.4.6` and this fix here (I guess never merged?) actually solves the problem.

**Comment by onlyjus** [comment]
same problem here with `poetry=1.1.7` and `virtualenv=20.4.6`, and this fix worked...

adding:
```
                if not name:
                    continue
```
to /poetry/repositories/installed_repository.py L118

**Pull request closed without merging**
