### PR TITLE
Update env remove logic

### PR DESCRIPTION
**Pull request by dhvcc**
# Pull Request Check List

Resolves: #6018 

- [X] Added **tests** for changed code.
- [X] Updated **documentation** for changed code. (no documentation change is needed I think)

### Changes

1. Added a check so that if `python` argument is a file (then it should be a python path) - extract it's venv name and raise `IncorrectEnvError` if it doesn't belong to this project
    **Before**
    ```
    └❯ poetry env remove ~/.cache/pypoetry/virtualenvs/different-project-OKfJHH_5-py3.10/bin/python
    /bin/sh: 1: different-project-OKfJHH_5-py3.10: not found

    Deleted virtualenv: ~/.cache/pypoetry/virtualenvs/poetry-4pWfmigs-py3.10
    ```
    Removes current project's env, which is wrong.
    **After**
    ```
    └❯ poetry env remove ~/.cache/pypoetry/virtualenvs/different-project-OKfJHH_5-py3.10/bin/python

    Env different-project-OKfJHH_5-py3.10 doesn't belong to this project.
    ```
2. Added the exact same check as before ^, but for cases where env name is passed.
    **Before**
    ```
    └❯ poetry env remove different-project-OKfJHH_5-py3.10      
     /bin/sh: 1: different-project-OKfJHH_5-py3.10: not found

     Command different-project-OKfJHH_5-py3.10 -c "import sys; print('.'.join([str(s) for s in sys.version_info[:3]]))" errored with the following return code 127, and output: 
    ```
    Errors while trying to exec env name as an interpreter, error is not clear.
    **After**
    ```
    └❯ poetry env remove different-project-OKfJHH_5-py3.10                      

    Env different-project-OKfJHH_5-py3.10 doesn't belong to this project.
    ```
3. Added a couple of tests for **new** and for **old** scenarios which weren't tested.
4. Added `venv_name` fixture for `tests/utils` directory to use in `test_env`. Also replaced some of `"simple-project"` hardcoded value to use `poetry.package.name`

It's up to maintainers to choose what they want for this project - I'm happy either way if we at least fix the bug. I can remove/change any of the stuff I added on top of the fix. But yeah I just decided that if we fix the bug, we might also make some improvements/changes in this area of code. Any thoughts on this are welcome, thanks!

### CODE REVIEW

**Review by neersighted — APPROVED** [review]

**Comment by neersighted** [comment]
I think this code could use a general refactor/cleanup to make it clear we now support 'identifiers' that can be Python version numbers, Python executable paths, or environment names (as well as maybe a docs pass). If you'd like to do that, it would be great -- if not, this is still incremental progress.

**Comment by dhvcc** [comment]
@neersighted yeah, I agree this could be a bit clearer in the code. I'd like to try to clean this up, wondering if there's any plan/ideas for it right now?

**Comment by neersighted** [comment]
Personally I would rework the code to actually be a simple `env.remove()` (actually using `self` to find the environment to remove) and then add functionality to `EnvManager` to find/create an `Env` instance for the identifier in question.

**Comment by neersighted** [comment]
If you're interested in working in this area still, #2748 might provide some more ideas for improvements to the CLI experience.

**Pull request merged**
