### PR TITLE
Add a --parallel flag to the install command

### PR DESCRIPTION
**Pull request by PetterS**
Tested this on our production codebase by installing from scratch two times:

Without this patch: 4 minutes and 22 seconds.
With --parallel: 1 minute and 8 seconds.

### CODE REVIEW

**Comment by PetterS** [comment]
Can of course not be merged since it does not support 2.7 among other things.

But I don't even know how to test this? How can I run the poetry code in my repo on another repository?

**Comment by PetterS** [comment]
Tested this on our production codebase by installing from scratch two times:

Without this patch: **4 minutes and 22 seconds**.
With --parallel: **1 minute and 8 seconds**.

Worked really well!

**Comment by ngryman** [comment]
👋   Hey folks, I just wanted to express explicit interest in this patch.

Our initial install times are floating around ~15 minutes. In comparison `poetry export | pip install` is around ~4 minutes. Unfortunately, the later one is 1) unreliable as `pip` regularly fails on "double requirements" errors and 2) should probably not become a widespread workaround to `poetry install`.

Is there anything we can do to bump the priority of this PR? Thanks in advance!

**Comment by PetterS** [comment]
I don't think there is an explicit process for getting someone in the core team to look at a PR.

For example, the uncontroversial PR https://github.com/python-poetry/poetry/pull/2375 has been waiting for review for a long time now.

Myself, I am maintaining my own personal fork of Poetry with a couple of extra patches like this one.   Would definitely prefer to merge something like this though.

**Comment by ngryman** [comment]
Hey @abn @finswimmer @sdispater @stephsamson, I'm explicitly raising your attention to this PR because I think it could really be beneficial for everyone.

We recently switched to use Poetry and we do love it! However our install times went from ~4 minutes to ~15 minutes which is starting to become a serious issue for us. These 10 more minutes quickly add up and our deployment pipelines and developer environment (we use Docker locally) got badly impacted performance-wise.

So now we're in this kind of situation where we do love the tool, but its performance is a big concern 😞

This PR cuts down install times by a factor of ~4 which is really a huge improvement 👏 . It seems that the change-set looks relatively straightforward, though I'm not an expert here. From my experience this kind of high-reward / low-risk PRs should be considered as high-priority since they don't involve that much time on the reviewer side.

Is there anything @PetterS or I could do to move things forward and help this PR to get merged?
Thanks in advance!

**Comment by sdispater** [comment]
Thanks for your contribution!

There is an ongoing work (see https://github.com/python-poetry/poetry/compare/develop...new-installer), to allow for parallel installations (with UI improvements to go with it) and other installation improvements, for instance downloading distributions separately.

The ultimate goal is to no longer rely on pip for the installation.

This will land in the next feature release as an experimental feature (activated with `poetry config experimental.new-installer true`). It's still in progress but I hope it will be available in the next alpha release of the `1.1` release.

**Comment by PetterS** [comment]
That's nice!

**Comment by sdispater** [comment]
Closing this PR since the PR for the new installer is now ready https://github.com/python-poetry/poetry/pull/2595

Thanks again for your contribution!

**Comment by PetterS** [comment]
Looks really great!

**Pull request closed without merging**
