### PR TITLE
Docs: adding a note about being able to specify a package's source repository

### PR DESCRIPTION
**Pull request by glencairn**
# Pull Request Check List

Resolves: #3476

- [ ] Added **tests** for changed code. (N/A)
- [x] Updated **documentation** for changed code.

---

Adding a little note to the documentation about the ability to specify the source repository for a dependency.

As mentioned in the linked issue, poetry's dependency resolution was failing because the first private repository poetry looked in for a specified dependency returned a 404. Whether or not that's the right behavior is a different discussion, but the problem can immediately be solved using the `source` property.

### CODE REVIEW

**Comment by sinoroc** [comment]
I link https://github.com/python-poetry/poetry/issues/3269 as somewhat related.

**Comment by glencairn** [comment]
@sinoroc, thanks for the link. I also updated the list of options in the documentation for the `poetry add` command since it was definitely missing several of the available options.

**Comment by lcbm** [comment]
Sorry in advance, if this isn't the right place to ask... also, if there's documentation on what I'm about to say, please LMK! I wasn't able to find anything on `source` _usage_ and it's _intended behavior_ :sob: 

It **is** clear to me, from the documentation in this MR, that one purpose of `source` is to specify, from a bunch of external sources I may have, which one I want to use for each specific package.

Before elaborating what **is not** clear to me, please consider the `pyproject.toml` below :point_down: 

```text
[tool.poetry.dependencies]
private-dependency = {version = "^1.0.0", source = "private-source"}

# and 'private-library' depends on a 'public-library' which is not in "private-source" (my private registry)

[[tool.poetry.source]]
name = "private-source"
url = "https://foo.bar/simple/"
default = true
```

It **is not** clear to me if:

1. `source` will enforce that `private-library` and all of its requirements are installed from `private-source` (as `pip` does with `--index-url`) OR if `source` will enforce that only `private-library` is installed from `private-source` and its requirements will be installed according to poetry's default behavior (**precedence** to `source` but will still look for the `private-dependency`'s dependencies in `pypi`);

2. let's say I have multiple `sources` in my `pyproject.toml` as well as multiple dependencies and each dependency is referencing their own source. If I want to ensure that each of my dependencies are looked up **exclusively** in their respective sources, can I all my sources with `default = true` under `[[tool.poetry.source]]`?

Lastly, I looked for an example `pyproject.toml` with multiple repositories [here](https://python-poetry.org/docs/repositories/) and couldn't find one... I'll drop a suggestion here to add a piece in this MR for that as well, considering that it's in that context that `source` should be used :smile:

**Comment by ggabriel96** [comment]
There's another PR doing this, https://github.com/python-poetry/poetry/pull/3400. It's just missing the CLI docs.

**Review by neersighted — DISMISSED** [review]

**Review by neersighted — APPROVED** [review]
Rebased onto current master. Just waiting on the CI to be unbroken to merge this (see #4753).

**Pull request merged**
