### PR TITLE
Create an official Poetry badge

### PR DESCRIPTION
**Pull request by johnthagen**
# Pull Request Check List

Resolves: #7270 

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

______

- The badge: [Poetry](https://python-poetry.org/)
- The badge is created following how [Ruff](https://github.com/charliermarsh/ruff) defines its logo, as described in https://github.com/python-poetry/poetry/issues/7270#issuecomment-1476106589.
- The message background color was extracted from the logo to match it.
- The `logoSvg` was taken directly from the official Poetry website repo: https://github.com/python-poetry/website/blob/main/static/images/logo-origami.svg 

To test embedding it (pointing to the current fork):

```
[![Poetry](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/johnthagen/poetry/poetry-badge/assets/badge/v0.json)](https://python-poetry.org/)
```

To embed it after merge:

```
[![Poetry](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/python-poetry/poetry/master/assets/badge/v0.json)](https://python-poetry.org/)
```

### CODE REVIEW

**Comment by radoering** [comment]
I'd say why not?

@Secrus I remember you had a strong opinion on that?

**Comment by Secrus** [comment]
I was working on one actually. 

@johnthagen I will get back to you on that during the weekend.

**Comment by Secrus** [comment]
Hey @johnthagen. Could you make this PR in [website](https://github.com/python-poetry/website) repo? I would leave it there and only make a docs entry about the badge availability here.

**Comment by johnthagen** [comment]
@Secrus Sure thing:

- https://github.com/python-poetry/website/pull/119

**Pull request closed without merging**
