### PR TITLE
[fix] inconsistent handling of symbolic links

### PR DESCRIPTION
**Pull request by zEdS15B3GCwq**
# Pull Request Check List

Resolves: #5425 describes some symptoms, but the root cause seems a bit more complicated.

- [+/-] Added **tests** for changed code. Well, not, but this fixes some failing tests.
- [ ] Updated **documentation** for changed code. No need.

In the code, paths (i.e. for file and directory package sources) are often _normalised_ using `Path.resolve()`. This "Make the path absolute, resolving any symlinks" ([quote](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve)). I've got the impression that the general expectation is that all of these locations should be normalised this way, however, _the code isn't completely consistent in this regard_. There are _some pathways in the code where location data isn't treated in the same way_, e.g. project root folders are used as supplied by `cwd`, which doesn't expand symbolic links. There are several tests as well, that do not take symbolic links into account.

Issue #5425 describes the problems I've noticed when coding or when executing Poetry tests in a folder that contained a symbolic link in the path. These are caused by:
1. `Locker` using `relpath` with _resolved_ package source but _unresolved_ project root paths, leading to unintended complicated relative paths (e.g. for a sub-module located under the project folder)
2. tests not taking symbolic links into account, supplying _unresolved_ paths to `Factory.add_dependency` and `Factory.create_dependency`, which don't _resolve_ them either
3. expected results in 1 test (`test_solver_can_resolve_directory_dependencies_nested_editable`) include _unresolved_ paths, causing test to fail because Poetry **does** _resolve_ those paths

In this PR I'm proposing simple fixes to points 1 and 3. The methods in point 2 are in _poetry-core's BaseFactory_, and although it doesn't require a complicated fix either, it's not as trivial a simply adding `resolve()` to a code line, at least not in here in _Poetry_, so I'm holding back until I get some feedback. Honestly, this entire thing is probably *not a high priority task*. I haven't had any real problems when *using* Poetry, except for the slightly annoying relative path in the locker file, and I haven't seen other related issues either. The only errors I've encountered are poetry's own tests failing. However, I do believe that the code is a bit sloppy in how it handles paths - path sanitization is left up to each module, which do that in different ways, sometimes resolving sometimes not, and test writers obviously didn't think of resolving paths either. My proposed code changes don't fix that. Therefore, yet unknown bugs may remain.

Some details about the failing tests I mentioned above:

_Pytest_ results in a folder that contains a symlink in its path:
```
    1011 passed
      15 failed
         - ..\Lib\poetry\tests\installation/test_installer.py:1321 test_run_installs_with_local_setuptools_directory
         - ..\Lib\poetry\tests\installation/test_installer.py:1287 test_run_installs_with_local_poetry_file_transitive
         - ..\Lib\poetry\tests\installation/test_installer.py:1255 test_run_installs_with_local_poetry_directory_transitive
         - ..\Lib\poetry\tests\installation/test_installer.py:1225 test_run_installs_with_local_poetry_directory_and_extras
         - ..\Lib\poetry\tests\installation/test_installer.py:1170 test_run_installs_with_local_file
         - ..\Lib\poetry\tests\installation/test_installer.py:1197 test_run_installs_wheel_with_no_requires_dist
         - ..\Lib\poetry\tests\installation/test_installer_old.py:860 test_run_installs_wheel_with_no_requires_dist
         - ..\Lib\poetry\tests\installation/test_installer_old.py:839 test_run_installs_with_local_file
         - ..\Lib\poetry\tests\installation/test_installer_old.py:907 test_run_installs_with_local_poetry_directory_transitive
         - ..\Lib\poetry\tests\installation/test_installer_old.py:939 test_run_installs_with_local_poetry_file_transitive
         - tests\puzzle/test_solver.py:2421 test_solver_can_resolve_sdist_dependencies_with_extras
         - tests\puzzle/test_solver.py:2493 test_solver_can_resolve_wheel_dependencies_with_extras
         - tests\puzzle/test_solver.py:2289 test_solver_can_resolve_directory_dependencies_nested_editable
         - tests\puzzle/test_solver.py:2461 test_solver_can_resolve_wheel_dependencies
         - tests\puzzle/test_solver.py:2389 test_solver_can_resolve_sdist_dependencies
       2 xfailed
       5 skipped
```

PR applied:
```
    1020 passed
       6 failed
         - ..\Lib\poetry\tests\installation/test_installer_old.py:860 test_run_installs_wheel_with_no_requires_dist
         - ..\Lib\poetry\tests\installation/test_installer_old.py:839 test_run_installs_with_local_file
         - tests\puzzle/test_solver.py:2389 test_solver_can_resolve_sdist_dependencies
         - tests\puzzle/test_solver.py:2421 test_solver_can_resolve_sdist_dependencies_with_extras
         - tests\puzzle/test_solver.py:2461 test_solver_can_resolve_wheel_dependencies
         - tests\puzzle/test_solver.py:2493 test_solver_can_resolve_wheel_dependencies_with_extras
       2 xfailed
       5 skipped
      21 deselected
```

9 tests are fixed. All the remaining fails are due to Point 2 above. Plus, after PR, relative paths in the locker file are correct (as in path to a sub-folder will be just the sub-folder's name, instead of pointing back to the sub-folder under symlink's target).

### CODE REVIEW

**Comment by zEdS15B3GCwq** [comment]
That failing check on [macOS / 3.11-dev](https://github.com/python-poetry/poetry/runs/7058973446?check_suite_focus=true) is a bit weird. It worked on the last commit, and the only difference since then is that the code was formatted by `black`.

**Comment by onerandomusername** [comment]
> That failing check on [macOS / 3.11-dev](https://github.com/python-poetry/poetry/runs/7058973446?check_suite_focus=true) is a bit weird. It worked on the last commit, and the only difference since then is that the code was formatted by `black`.

This occurred on another pr too, I think it was the same error as well.

**Comment by zEdS15B3GCwq** [comment]
> > That failing check on [macOS / 3.11-dev](https://github.com/python-poetry/poetry/runs/7058973446?check_suite_focus=true) is a bit weird. It worked on the last commit, and the only difference since then is that the code was formatted by `black`.
> 
> This occurred on another pr too, I think it was the same error as well.

Any idea how to fix it?

I'm happy to spend more time to figure it out when this becomes the main hurdle to this PR being accepted.

**Comment by spoorn** [comment]
I just noticed, I had already submitted a PR for this same fix, except I added some extra tests for it: https://github.com/python-poetry/poetry/pull/5850

**Comment by neersighted** [comment]
Duplicated #5850 which is merged

**Pull request closed without merging**
