### PR TITLE
Parse double quoted version in constraints

### PR DESCRIPTION
**Pull request by abn**
Resolves: #2119

# Pull Request Check List

- [x] Added **tests** for changed code.

Documentation changes not required.

### CODE REVIEW

**Comment by finswimmer** [comment]
Hello @abn,

thanks a lot for contribution. Your change looks good to me.

I'm hesitating a bit to vote for merging it. The reason is, that I'm not sure if quoted version in constraint are allowed or not. While it is technical quite easy to implement, I prefer being compliant to existing rules. Do you know any source that might clarify this?

fin swimmer

**Comment by abn** [comment]
@finswimmer [PEP-508](https://www.python.org/dev/peps/pep-0508/#examples) does mention the use of this. Note that the PEP is informaitonal. This is particular to the specification of dependencies.

**Comment by sdispater** [comment]
@abn Actually the version specification is documented by the PEP 440 and having quotes in the constraint is not valid as far as I know.

After investigation a bit, it seems that there is an issue with the metadata of `openapi-core`:

```
Metadata-Version: 2.1
Name: openapi-core
Version: 0.13.2
Summary: UNKNOWN
Home-page: https://github.com/p1c2u/openapi-core
Author: Artur Maciag
Author-email: maciag.artur@gmail.com
License: UNKNOWN
Keywords: openapi,swagger,schema
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Intended Audience :: Developers
Classifier: Topic :: Software Development :: Libraries :: Python Modules
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Topic :: Software Development :: Libraries
Requires-Python: !=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,>=2.7
Description-Content-Type: text/x-rst; charset=UTF-8
Requires-Dist: openapi-spec-validator
Requires-Dist: six
Requires-Dist: lazy-object-proxy
Requires-Dist: strict-rfc3339
Requires-Dist: isodate
Requires-Dist: attrs
Requires-Dist: werkzeug
Requires-Dist: backports.functools-lru-cache ; python_version < "3.0"
Requires-Dist: backports.functools-partialmethod ; python_version < "3.0"
Provides-Extra: django
Requires-Dist: django (>=2.2) ; extra == 'django'
Requires-Dist: python-version (>="3.0") ; extra == 'django'
Provides-Extra: flask
Requires-Dist: flask ; extra == 'flask'
``` 

The line that is causing the issue is this one:

```
Requires-Dist: python-version (>="3.0") ; extra == 'django'
```

As you can see, there is something wrong with how they specify their metadata which leads to this erroneous line.

**Comment by abn** [comment]
@sdispater that is the correct root cause. The fix was a bit pre-mature. Closing this one.

The fix here should be in openapi-core, the line:

https://github.com/p1c2u/openapi-core/blob/18944893f755f910a747c80e35545292fab9c1d6/setup.cfg#L47-L50

Should be rewritten as:
```cfg
[options.extras_require]
django = 
    django>=2.2; python_version>="3.0"
flask = flask
```

**Comment by zupo** [comment]
@abn: do you mean it should be rewritten as `django>=2.2; python_version>=3.0`? Your example is exactly how `setup.cfg` is currently writtetn.

**Comment by abn** [comment]
@zupo the relevant change is the addition of the new line and the indent. This should force `ConfigParser` to treat the value as a list, which translates to (what I think the project author intended) in the package `METADATA`.

```
Provides-Extra: django
Requires-Dist: django (>=2.2) ; (python_version >= "3.0") and extra == 'django'
Provides-Extra: flask
Requires-Dist: flask ; extra == 'flask'
```
This version as opposed to the one you can see in https://github.com/python-poetry/poetry/pull/2144#issuecomment-596145668 detected the environment markup correctly and not as the package [python-version](https://pypi.org/project/python_version/) with a version constraint that is invalid according to [PEP-440](https://www.python.org/dev/peps/pep-440).

Hope this helps calrify the situation.

**Pull request closed without merging**
