### PR TITLE
Include platform option in documentation: #1189 #738

### PR DESCRIPTION
**Pull request by deepio**
# Pull Request Check List

~~- [ ] Added **tests** for changed code.~~
- [x] Updated **documentation** for changed code.

### If it's a bug fix or only a documentation update, it should be based on the `master` branch.

#1189 #738 
It is unclear that dependencies specific to a platform can be handled by poetry.

### CODE REVIEW

**Comment by jimbo1qaz** [comment]
This is wrong.
- it must match `sys.platform`. You should mention this in the documentation.
- sys.platform is "win32" not "windows".

**Comment by deepio** [comment]
> This is wrong, unless poetry has changed since the last time i checked, or unless i was wrong in #738.
> 
> * it must match `sys.platform`. You should mention this in the documentation.
> * sys.platform is "win32" not "windows".

You're right, fixed.

**Comment by deepio** [comment]
/ unstale

**Comment by finswimmer** [comment]
Hello,

these changes are now obsolete, because content is removed from README and is only available in the docs.

Thanks a lot for your suggestions!

fin swimmer

**Pull request closed without merging**
