### PR TITLE
Improve password management

### LINKED ISSUE #1335: Keyring error on every command
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 30 Gnome
- **Poetry version**: 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/lpfann/d452508a400b15d63091e18d25e964f6

## Issue
On the latest beta release I encounter the following output when running any poetry command.
Poetry still works fine despite those messages.
It is probably related to #774 .

```
Error initializing plugin EntryPoint('Gnome', 'keyrings.alt.Gnome', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/Gnome.py", line 11, in <module>
    from keyring.py27compat import unicode_str
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('Google', 'keyrings.alt.Google', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/Google.py", line 18, in <module>
    from keyring.py27compat import input, pickle
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/file_base.py", line 7, in <module>
    from keyring.py27compat import configparser
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/file.py", line 9, in <module>
    from keyring.py27compat import configparser
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('kwallet', 'keyrings.alt.kwallet', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/kwallet.py", line 6, in <module>
    from keyring.py27compat import unicode_str
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/pyfs.py", line 5, in <module>
    from keyring.py27compat import configparser
ModuleNotFoundError: No module named 'keyring.py27compat'
```

### LINKED ISSUE #1565: poetry 1.0.0b4 hangs
```
$ poetry self:update --preview
Updating to 1.0.0b4
 - Downloading poetry-1.0.0b4-linux.tar.gz 100%

Poetry (1.0.0b4) is installed now. Great!
```

When I try to start poetry, it hangs, nothing happens:

    $ poetry

Then, if I terminate it with Ctrl+C, this is the output I get:

```
^CTraceback (most recent call last):
  File "/home/jabba/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/home/jabba/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/jabba/.poetry/lib/poetry/console/application.py", line 5, in <module>
    from .commands.about import AboutCommand
  File "/home/jabba/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/jabba/.poetry/lib/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/home/jabba/.poetry/lib/poetry/factory.py", line 17, in <module>
    from .packages.dependency import Dependency
  File "/home/jabba/.poetry/lib/poetry/packages/__init__.py", line 7, in <module>
    from .dependency import Dependency
  File "/home/jabba/.poetry/lib/poetry/packages/dependency.py", line 10, in <module>
    from poetry.utils.helpers import canonicalize_name
  File "/home/jabba/.poetry/lib/poetry/utils/helpers.py", line 11, in <module>
    from keyring import delete_password
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/core.py", line 189, in <module>
    init_backend()
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/core.py", line 91, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/util/__init__.py", line 22, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 204, in get_all_keyring
    return list(rings)
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/util/__init__.py", line 33, in suppress_exceptions
    for callable in callables:
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 64, in viable
    cls.priority
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/backends/SecretService.py", line 41, in priority
    list(secretstorage.get_all_collections(bus))
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/secretstorage/collection.py", line 153, in get_all_collections
    for collection_path in service.get_property('Collections'):
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/secretstorage/util.py", line 65, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/secretstorage/util.py", line 47, in send_and_get_reply
    return self._connection.send_and_get_reply(msg)
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/jeepney/integrate/blocking.py", line 67, in send_and_get_reply
    self.recv_messages()
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/jeepney/integrate/blocking.py", line 55, in recv_messages
    b = self.sock.recv(4096)
KeyboardInterrupt
```

Environment: Manjaro Linux, Python 3.7

### LINKED ISSUE #1719: ModuleNotFoundError for keyring.util.escape in Docker image (poetry 1.0.0 and 1.0.0b9)
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.14.6, running docker. Docker image is `nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04`
- **Poetry version**: Both 1.0.0b9 and 1.0.0

## Issue

Attempted an install of poetry in my docker file. The install succeeds, but running any poetry commands gives a strange error. I've shown the docker build (trimmed down) along with the error below.

Docker Build output (Trimmed down for brevity): 
```
Setting up container for folder or workspace: /Users/ryan.butler/Programming/robotics
Run: docker build -f /Users/ryan.butler/Programming/robotics/Dockerfile -t vsc-robotics-14e00cfc95af169a4eb8b5156cec6517 /Users/ryan.butler/Programming/robotics
Sending build context to Docker daemon  115.4MB
Step 1/44 : FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
 ---> 81c7dbc267d8
....................................
Step 11/44 : RUN  update-alternatives --install /usr/bin/python python /usr/bin/python3 10   && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
 ---> Using cache
 ---> 0cb8d16b47b8
.....................................
Step 18/44 : USER ${USERNAME}
 ---> Using cache
 ---> e18c506cbcad
......................................
Step 27/44 : SHELL ["/bin/zsh", "-c"]
 ---> Using cache
 ---> 426fe465c653
.......................................
Step 33/44 : ENV PY_USER_BIN="/home/${USERNAME}/.local/bin"
 ---> Using cache
 ---> 28e257b22543
Step 34/44 : RUN echo "PY_USER_BIN=$PY_USER_BIN"
 ---> Using cache
 ---> 9f22bf26abcc
Step 35/44 : ENV PATH=$PY_USER_BIN:$PATH
 ---> Using cache
 ---> ef605d0626e3
Step 36/44 : RUN pip list | grep keyring
 ---> Running in 9528402aa43c
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
keyring (10.6.0)
keyrings.alt (3.0)
Removing intermediate container 9528402aa43c
 ---> 294fa116e934
Step 37/44 : ENV PATH="/home/${USERNAME}/.poetry/bin:$PATH"
 ---> Running in b1b79a218bcc
Removing intermediate container b1b79a218bcc
 ---> 596f1ba898f6
Step 38/44 : RUN which python && which pip
 ---> Running in a5f223ed10f2
/usr/bin/python
/usr/bin/pip
Removing intermediate container a5f223ed10f2
 ---> 6fd46b40f5ee
Step 39/44 : RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
 ---> Running in eb812cbd3c07
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.
.................................................

Poetry (1.0.0) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`

Removing intermediate container eb812cbd3c07
 ---> b0cfd3ab6a72
Step 40/44 : RUN which poetry
 ---> Running in 459a6af62814
/home/saicny/.poetry/bin/poetry
Removing intermediate container 459a6af62814
 ---> 3e2a9b083675
Step 41/44 : RUN poetry
 ---> Running in be08c33c0095
Traceback (most recent call last):
  File "/home/saicny/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/saicny/.poetry/lib/poetry/_vendor/py3.6/importlib_metadata/__init__.py", line 92, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saicny/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/home/saicny/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/saicny/.poetry/lib/poetry/console/application.py", line 5, in <module>
    from .commands.about import AboutCommand
  File "/home/saicny/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/saicny/.poetry/lib/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/home/saicny/.poetry/lib/poetry/factory.py", line 17, in <module>
    from .packages.dependency import Dependency
  File "/home/saicny/.poetry/lib/poetry/packages/__init__.py", line 7, in <module>
    from .dependency import Dependency
  File "/home/saicny/.poetry/lib/poetry/packages/dependency.py", line 10, in <module>
    from poetry.utils.helpers import canonicalize_name
  File "/home/saicny/.poetry/lib/poetry/utils/helpers.py", line 11, in <module>
    from keyring import delete_password
  File "/home/saicny/.poetry/lib/poetry/_vendor/py3.6/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/home/saicny/.poetry/lib/poetry/_vendor/py3.6/keyring/core.py", line 192, in <module>
    init_backend()
  File "/home/saicny/.poetry/lib/poetry/_vendor/py3.6/keyring/core.py", line 96, in init_backend
    filter(limit, backend.get_all_keyring()),
  File "/home/saicny/.poetry/lib/poetry/_vendor/py3.6/keyring/util/__init__.py", line 22, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/saicny/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 216, in get_all_keyring
    _load_plugins()
  File "/home/saicny/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 207, in _load_plugins
    log.exception("Error initializing plugin %s." % ep)
TypeError: not all arguments converted during string formatting
The command '/bin/zsh -c poetry' returned a non-zero code: 1
Failed: Building an image from the ../Dockerfile (this can take a while).
Command failed: docker build -f /Users/ryan.butler/Programming/robotics/Dockerfile -t vsc-robotics-14e00cfc95af169a4eb8b5156cec6517 /Users/ryan.butler/Programming/robotics

### LINKED ISSUE #1779: Invoking poetry with no arguments takes up to two minutes to complete
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.3
- **Poetry version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: This can occur without a project.

## Issue

I have installed poetry in pipx which is using python 3.7.4 using the command:

`pipx install poetry`

When I invoke `poetry` it takes up to 2 minutes to print the default help text.
If I cancel it while it is doing this then the stack trace shows it using jeepney to load secrets?

```
➜ poetry
^CTraceback (most recent call last):
  File "/home/matthew/.local/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/poetry/console/application.py", line 5, in <module>
    from .commands.about import AboutCommand
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/poetry/factory.py", line 17, in <module>
    from .packages.dependency import Dependency
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/poetry/packages/__init__.py", line 7, in <module>
    from .dependency import Dependency
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/poetry/packages/dependency.py", line 10, in <module>
    from poetry.utils.helpers import canonicalize_name
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/poetry/utils/helpers.py", line 11, in <module>
    from keyring import delete_password
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/core.py", line 192, in <module>
    init_backend()
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/core.py", line 96, in init_backend
    filter(limit, backend.get_all_keyring()),
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/util/__init__.py", line 22, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/backend.py", line 219, in get_all_keyring
    return list(rings)
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/util/__init__.py", line 33, in suppress_exceptions
    for callable in callables:
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/backend.py", line 68, in viable
    cls.priority
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/keyring/backends/SecretService.py", line 41, in priority
    list(secretstorage.get_all_collections(bus))
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/secretstorage/collection.py", line 153, in get_all_collections
    for collection_path in service.get_property('Collections'):
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/secretstorage/util.py", line 65, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/secretstorage/util.py", line 47, in send_and_get_reply
    return self._connection.send_and_get_reply(msg)
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/jeepney/integrate/blocking.py", line 67, in send_and_get_reply
    self.recv_messages()
  File "/home/matthew/.local/pipx/venvs/poetry/lib/python3.7/site-packages/jeepney/integrate/blocking.py", line 55, in recv_messages
    b = self.sock.recv(4096)
KeyboardInterrupt
```

### PR DESCRIPTION
**Pull request by sdispater**
## Pull Request Check List

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

This PR is a refactoring of the password management of Poetry. This alleviates some of the `keyring` shortcomings and delays the import of `keyring` to only
 when it's needed to avoid the CLI hanging because of it (see #1779).

Fixes #1779
Fixes #1719 
Fixes #1565
Fixes #1335

### CODE REVIEW

**Comment by K900** [comment]
Would be really nice to see the `keyring` dependency bumped to something like `>=19.0` on Python 3. It makes source built Poetry not run on Arch...

**Comment by Ivoz** [comment]
Unfortunately keyring 19.0 drops python 2.7, so you'd have to figure out what you want to do about that

**Comment by danieleades** [comment]
hi there, i'm still seeing these issues on ubuntu 18.04.

the system library of `keyrings.alt` is being picked up, and it's trying to import `keyring.util.escape`, which doesn't exist in the vendored version of `keyring` (but does in the system version). Does this merge *really* fix the root cause of #1719 and #1335, or does it just postpone the import so that only *some* commands are broken?

If there's any other details i can provide, or a more appropriate place to report this, please let me know!

**Comment by christian-hawk** [comment]
Happens on github actions ubuntu/latest too.

**Pull request merged**
