### PR TITLE
package: allow url dependencies to be optional

### LINKED ISSUE #2255: Optional URL dependency is locked as non-optional
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: See reproduction below.

## Issue

When adding an optional URL dependency to the project, I specify it like so:

```toml
[tool.poetry.dependencies]
rethinkdb = { optional = true, url = "https://github.com/tommilligan/rethinkdb-python/releases/download/v2.4.5.post1/rethinkdb-2.4.5.post1-py2.py3-none-any.whl" }
```

However, after locking, this results in a lockfile like:

```toml
[[package]]
category = "main"
description = "Python driver library for the RethinkDB database server."
name = "rethinkdb"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
version = "2.4.5.post1"

[package.dependencies]
six = "*"
```

Note that the lock marks this package as **`optional = false`**. I would expect this to be **`true`**.

### PR DESCRIPTION
**Pull request by tommilligan**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://python-poetry.org/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [ ] ~Updated **documentation** for changed code.~ **N/A**

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

---

This PR allows URL dependencies to be marked as optional in `pyproject.toml`. It updates `package.py` and adds a unit test for this case (fails on current master).

I also tested this locally against a real world case, and found it resolved my issue.

Closes #2255

### CODE REVIEW

**Comment by abn** [comment]
Since the schema already allows for this, this is a bug.

https://github.com/python-poetry/core/blob/master/poetry/core/json/schemas/poetry-schema.json#L408-L443

**Comment by tommilligan** [comment]
No problem, thanks for the quick merge.

**Comment by abn** [comment]
@tommilligan I have also ported your commit to python-poetry/core project as well so that the next release will retain the fix.

**Comment by tommilligan** [comment]
Thanks - looks like this is an ongoing refactor? For my reference, what will be in `core` in future?

**Pull request merged**
