### PR TITLE
Normalize author name unicode before matching

### LINKED ISSUE #2004: 'ë' in author name raise an error during `poetry install`
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: -
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/raphaelyancey/3d6ffeaddb75d5a96c173bab51e3688c

## Issue

```bash
$ poetry install -v

Using virtualenv: /Users/raphael/Library/Caches/pypoetry/virtualenvs/pyky040-oonWdb9N-py3.7
Installing dependencies from lock file

No dependencies to install or update

  - Skipping zipp (1.1.0) Already installed
  - Skipping importlib-metadata (1.5.0) Already installed
  - Skipping pyparsing (2.4.6) Already installed
  - Skipping six (1.14.0) Already installed
  - Skipping atomicwrites (1.3.0) Already installed
  - Skipping attrs (19.3.0) Already installed
  - Skipping colorama (0.4.3) Not needed for the current environment
  - Skipping more-itertools (8.2.0) Already installed
  - Skipping packaging (20.1) Already installed
  - Skipping pluggy (0.13.1) Already installed
  - Skipping py (1.8.1) Already installed
  - Skipping wcwidth (0.1.8) Already installed
  - Skipping pytest (4.6.9) Already installed
  - Not removing pathlib2 (2.3.5) Not currently installed

[AttributeError]
'NoneType' object has no attribute 'group'

Traceback (most recent call last):
  File "/Users/raphael/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/raphael/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/raphael/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/raphael/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/raphael/.poetry/lib/poetry/console/commands/install.py", line 72, in handle
    builder = EditableBuilder(self.poetry, self._env, NullIO())
  File "/Users/raphael/.poetry/lib/poetry/masonry/builders/builder.py", line 70, in __init__
    self._meta = Metadata.from_package(self._package)
  File "/Users/raphael/.poetry/lib/poetry/masonry/metadata.py", line 54, in from_package
    meta.author = package.author_name
  File "/Users/raphael/.poetry/lib/poetry/packages/package.py", line 137, in author_name
    return self._get_author()['name']
  File "/Users/raphael/.poetry/lib/poetry/packages/package.py", line 165, in _get_author
    name = m.group('name')
```

The error is gone when I replace `ë` by `e` in my name in `pyproject.toml`.

### PR DESCRIPTION
**Pull request by raphaelyancey**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://python-poetry.org/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code. (not needed)

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

Fixes #2004

### CODE REVIEW

**Comment by raphaelyancey** [comment]
@Behemyth Any idea why the linting failed? Is there somerthing I can do, or I did wrong?

**Comment by Behemyth** [comment]
You can probably test linting locally with 
```
pip install pre-commit
pre-commit run --all-files
``` 

(taken from `poetry/.github/workflows/main.yml`)

**Comment by finswimmer** [comment]
Hello @raphaelyancey,

you need to run `isort` and `black` on the changed files (or the whole `poetry` and `tests` folder) before the commit. This is what I do:

```
isort -rc poetry
isort -rc tests
black poetry
black tests
```

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
