### PR TITLE
chore: enable pep 563/585

### PR DESCRIPTION
**Pull request by branchvincent**
This enables [PEP 563](https://www.python.org/dev/peps/pep-0563/) and [PEP 585](https://www.python.org/dev/peps/pep-0585/) :fire:

Blocked by #5055
Relates-To: #4997

### CODE REVIEW

**Comment by neersighted** [comment]
I think this might be a bit too aggressive -- is the new union syntax really available? I see all the tests pass, but according to [PEP 604](https://www.python.org/dev/peps/pep-0604/) this wasn't added til 3.10. My memory is a bit rusty however.

**Comment by branchvincent** [comment]
Yea, you're right technically `x: int | str` is a syntax error for <3.10. However, with `from __future__ import annotations` this becomes equivalent to `x: "int | str"`. So by default it's not evaluated at run-time, but [mypy knows how to interpret it](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-x-y-syntax-for-unions).

I should have noted that `pyupgrade` [handled this migration](https://github.com/asottile/pyupgrade#pep-585-typing-rewrites), the only other change here was removing unused imports (for which I used [pycln](https://github.com/hadialqattan/pycln)).

**Comment by neersighted** [comment]
A second PR adding `pycln` to the pre-commit config would be welcome, I think.

Consensus seems to be that the new Union syntax is harmless and nicer to write. Let's go ahead with this.

**Review by neersighted — APPROVED** [review]
Approved, but I'd like to wait for at least one other maintainer to eyeball this before we merge.

**Comment by danieleades** [comment]
I don't hate this. I've got a *feeling* that the `pyupgrade` hook can also add the `from __future__ import annotations` line, but perhaps only on later targets (maybe 3.9?). Not sure if anyone can confirm or deny that.

**Comment by branchvincent** [comment]
> `pyupgrade` hook can also add the `from __future__ import annotations` line

I checked, it can definitely [remove them](https://github.com/asottile/pyupgrade#__future__-import-removal), but I can't find any indication of it adding them. See https://github.com/asottile/pyupgrade/issues/255#issuecomment-753509147 for an explanation of why it doesn't support that

**Comment by branchvincent** [comment]
rebased due to conflicts

**Review by neersighted — APPROVED** [review]

**Pull request merged**
