### PR TITLE
issue-3040: Hides traceback for SolverProblemError

### PR DESCRIPTION
**Pull request by lowitea**
# Pull Request Check List

Resolves: #3040

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by abn** [comment]
@lowitea any chance we can add a test case for this somewhere?

**Comment by lowitea** [comment]
@abn i couldn't think of how to do it :(

**Comment by lowitea** [comment]
@abn Hi
Is it possible to take this without tests?

**Comment by abn** [comment]
Looks like the solution is not being displayed (this bit).

```
  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For black, a possible solution would be to set the `python` property to ">=3.6,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

```sh
podman run --rm -i --entrypoint bash python:3.8 <<EOF
set -xe
python -m pip install -q git+https://github.com/python-poetry/poetry.git@refs/pull/3111/head
install -d foobar
cat > pyproject.toml <<TOML
[tool.poetry]
name = "foobar"
version = "0.1.0"
description = ""
authors = ["Your Name <your.name@example.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
TOML
poetry add black
EOF
```
### Output
```console
+ python -m pip install -q git+https://github.com/python-poetry/poetry.git@refs/pull/3111/head
  WARNING: Did not find branch or tag 'refs/pull/3111/head', assuming revision or ref.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
+ install -d foobar
+ cat
+ poetry add black
Creating virtualenv foobar-il7asoJj-py3.8 in /root/.cache/pypoetry/virtualenvs
Using version ^20.8b1 for black

Updating dependencies
Resolving dependencies...
The current project's Python requirement (>=3.5,<4.0) is not compatible with some of the required packages Python requirement:
  - black requires Python >=3.6, so it will not be satisfied for Python >=3.5,<3.6

Because no versions of black match >20.8b1,<21.0
 and black (20.8b1) requires Python >=3.6, black is forbidden.
So, because foobar depends on black (^20.8b1), version solving failed.
```

**Comment by lowitea** [comment]
Let me check. I’ll contact you later.

**Comment by neersighted** [comment]
Closing this as we've removed the default tracebacks with a Cleo change.

**Pull request closed without merging**
