### PR TITLE
Add additional method for CI installation using `pip-tools`

### PR DESCRIPTION
**Pull request by nikitabarskov**
I add the additional way to install `poetry` in CI environments.

It uses `pip-tools`, and `requirements.txt` with hashes. So, the level of reproducibility is quite high.

I've developed it with my colleague @aucampia, and we widely use it with a high level of success, so I decided to share it with the Poetry community.

I'm glad to hear your feedback!

### CODE REVIEW

**Comment by Secrus** [comment]
This goes against the recommended way of working with Poetry, which is to install Poetry into a separate environment from your project.

**Comment by Secrus** [comment]
Ok, I am puzzled. Why would you mix Poetry with pip-tools? What is the reason for it?

**Comment by nikitabarskov** [comment]
> Ok, I am puzzled. Why would you mix Poetry with pip-tools? What is the reason for it?

There was no way to have an analog of `lockfile` when I wanted to install Poetry. To some extent, it might be considered an over-engineered solution.

But basically, the usage of `pip-tools` allows me to generate a `requirements.txt` with hashes containing dependencies only for Poetry. Then I use this `requirements.txt` to install Poetry within my CI/CD pipelines or development images.

You can take a look at the public example I have at my current workplace:

- the Dockerfile https://github.com/coopnorge/engineering-docker-images/blob/main/images/poetry-python3.11/context/Dockerfile

- and the commands https://github.com/coopnorge/engineering-docker-images/blob/main/images/poetry-python3.11/context/Makefile#L14-L23 I used to generate `requirements-poetry.txt` https://github.com/coopnorge/engineering-docker-images/blob/main/images/poetry-python3.11/context/requirements-poetry.txt

**Comment by nikitabarskov** [comment]
As a side effect, with this approach later you can configure @dependabot or @renovatebot to update the `requirements-poetry.in` at almost 0 costs :)

**Comment by Secrus** [comment]
Ok. While we are grateful for your contribution, we don't know `pip-tools` and don't want to carry the support burden when we introduce this in docs. We plan on providing a `requirements.txt`-like lockfile for Poetry installation but based on `pip` alone.

**Comment by nikitabarskov** [comment]
> Ok. While we are grateful for your contribution, we don't know `pip-tools` and don't want to carry the support burden when we introduce this in docs. We plan on providing a `requirements.txt`-like lockfile for Poetry installation but based on `pip` alone.

This is excellent news for us! We also want to reduce the maintenance burden for our reproducible builds.

**Pull request closed without merging**
