### PR TITLE
Update 'packaging' 20.4 -> 20.8

### LINKED ISSUE #3458: Poetry does not install from wheels on macOS Big Sur
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.0.1 on Apple Silicon
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/crimsobot/crimsoBOT/blob/c00966011f5e829c097f0f1ce77e0b785d0d23ab/pyproject.toml

## Issue

When using Poetry on Big Sur, `poetry.installation.chooser.Chooser` is not recognizing available macOS wheels.
e.g. Poetry uses `cryptography-3.0.tar.gz` instead of `cryptography-3.0-cp27-cp27m-macosx_10_10_x86_64.whl`.

This has been fixed in https://github.com/pypa/packaging/pull/319 (v20.5 and above), however it appears that Poetry is using packaging v20.4.
I've tracked it down to https://github.com/python-poetry/poetry-core vendoring in packaging v20.4, as `poetry.utils.env.VirtualEnv.get_supported_tags` is using `~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/_vendor/packaging/tags.py` as the script source on my machine.

I'm happy to put up a PR for this both here and in poetry-core, I just wasn't sure how to proceed with the vendoring there and how it ties back to here.

If there's any clarification I can provide, let me know :)

### PR DESCRIPTION
**Pull request by emanueljacob**
closes #3458

# Pull Request Check List

Resolves: #3458

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by barentsen** [comment]
I tried this fix by installing `poetry@pr3530` on OSX Big Sur v11.1 in an Intel x86 terminal as follows:
```
pipx install --suffix @pr3530 'poetry @ git+https://github.com/emanueljacob/poetry@dev/update-packaging-20-8'
```
...however I found that `poetry@pr3530 install` continued to install packages like numpy and scipy from source rather than from their wheels, i.e. this PR did not appear to fix the issue for me.

I do not have a deep understanding of the internals of `poetry`, however I suspect it is `vendors/pyproject.toml` over in `poetry-core` we need to update:

https://github.com/python-poetry/poetry-core/blob/master/vendors/pyproject.toml

Changing that file to require `packaging = "^20.8"`, followed by running `make vendor/sync` and `pip install .` in the root of `poetry-core` fixed #3458 for me.

**Comment by henryiii** [comment]
Is there a way to help with this? Poetry on macOS Big Sur (the Intel version) cannot install binary wheels; since NumPy doesn't build out of the box on macOS, this means no NumPy in poetry. :'( Bumping to 20.8 will fix Intel Big Sur (and the next release will fix Apple Silicon Big Sur).

**Comment by alexifm** [comment]
This PR only changes the lock file.  It needs to update the pyproject.toml file.  

@barentsen is correct, poetry-core needs to be updated too.  [PR 125](https://github.com/python-poetry/poetry-core/pull/125) seems to do it but I haven't fully tested.  

Here's how I got pipx to work:
```
$ pipx install --suffix @pr3530 'poetry @ git+https://github.com/alexifm/poetry@packaging-20-8'
$ rm -rf ~/.local/pipx/venvs/poetry@pr3530/lib/python3.8/site-packages/poetry_core* \
   ~/.local/pipx/venvs/poetry@pr3530/lib/python3.8/site-packages/poetry/core  # injection wouldn't overwrite.  had to manually clear it out.  Maybe a pip uninstall would work?
$ pipx inject poetry@pr3530 'poetry-core @ git+https://github.com/gi0baro/poetry-core@packaging-20-8'
$ cat /Users/alexifm/.local/pipx/venvs/poetry@pr3530/lib/python3.8/site-packages/poetry/core/_vendor/packaging/__about__.py| grep "__version__ ="      
__version__ = "20.8"
```

**Comment by alexifm** [comment]
Was able to test on another machine with Big Sur.  Didn't seem to work.

**Comment by gi0baro** [comment]
> Was able to test on another machine with Big Sur. Didn't seem to work.

@alexifm do you have any details?

**Comment by alexifm** [comment]
> @alexifm do you have any details?

Yea, I guess "it didn't work" isn't helpful.  But unfortunately I don't have much else to say.  Installing numpy worked but it took a while so I suspected it wasn't a wheel.  I tried pyarrow instead and that confirmed it was compiling the source.  I don't really know what else to look for.  I couldn't see anything in the verbose poetry logs that indicated anything about wheel vs source.

**Comment by henryiii** [comment]
I just tested the lines above (on Python 3.9, but otherwise the same), and it worked just fine. NumPy installed in about 2 seconds (and NumPy can't build from source in the default environment, I haven't set up the site cfg or variables requires to build it on macOS).

**Comment by alexifm** [comment]
Okay, so I botched a couple of things.  One of them really dumb and not something I want to talk about.  But, I got it to work.  One key thing is pip needs to be updated too, naturally.  The other is there actually needs to be a wheel for the package (pyarrow doesn't have a wheel for 3.9)

**Comment by alexifm** [comment]
I did another test: I just installed the latest published poetry.  New first line in the steps above:
```
$ pipx install --suffix @pr125  'poetry'
```
Worked just fine.  Seems like we just need to get @gi0baro's PR merged in and then upgrade to the new poetry-core.

**Comment by ryboe** [comment]
The fix has landed in `poetry-core` 1.0.2, but `poetry` is still using `poetry-core` 1.0.0. Can we bump the `poetry-core` version please?

**Comment by henryiii** [comment]
I just got my M1 machine a few minutes ago, I can test something if helpful. I released boost-histogram with a Universal2 wheel, but it depends on NumPy, so can't use it without system site packages yet. :/

**Comment by max-sixty** [comment]
If a project changes from poetry to:
```
requires = ["poetry-core>=1.0.2"]
```

...will Big Sur work for that package without an update to this repo?

**Comment by ryboe** [comment]
Unfortunately, no, @max-sixty. `poetry` needs to update `poetry-core` itself.

**Comment by jrmlhermitte** [comment]
Looks like this was done [here](https://github.com/python-poetry/poetry/commit/6f70c3e257cdd97d41b82ba26267ee753230a39e)  9 days ago and so this is no longer needed?

Does anyone know when this latest version will be released with this commit?

**Comment by max-sixty** [comment]
What would it take to make a release, assuming that's what's require for poetry to work with Big Sur?

**Comment by gi0baro** [comment]
FYI I just published a binary version of Poetry that _might solve the issue_ on Big Sur (intel).
Mind that it also _might introduce other issues_, so use it at your own risk :)
https://github.com/gi0baro/poetry-bin

**Comment by jrmlhermitte** [comment]
Looks like this is fixed in https://github.com/python-poetry/poetry/releases/tag/1.1.5
from https://github.com/python-poetry/poetry/pull/3677
and that this PR may not be needed anymore.

I have tested this version and I am now downloading wheels rather than building from source for the packages I would expect.

Thanks for the discussion and thanks @sdispater for having released this fix.

**Comment by abn** [comment]
Closing this as this does not seem to be needed anymore as per above comments.

**Pull request closed without merging**
