### PR TITLE
Add docs for multiple maintainers example

### PR DESCRIPTION
**Pull request by gunungpw**
# Pull Request Check List

Resolves: None

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

- add an example for multiple maintainers in `pyproject.toml` section
- fix license example position for consistency with other example (before *NOTE*)

### CODE REVIEW

**Comment by Secrus** [comment]
Hi. Why do you think this change is needed? IMO docs state clearly, that `maintainers` is a list of maintainers. I would understand that change if the `maintainers` field was either single or multiple values.

**Comment by gunungpw** [comment]
Hello @Secrus although the documentation said this was a list of maintainers, from the perspective of new user who first time learn packaging their library/app or new to python. That was not clear how to write multiple maintainer list (formatting, toml syntax, trailing comma) and poetry it's self not yet support [PEP 621](https://peps.python.org/pep-0621/) metadata. For me who have little understanding of packaging in python, documentation that have example that can be copy-paste will help a lot.
I also agree maybe we should use just multiple maintainer example.
Thank you ❤️

**Comment by Secrus** [comment]
@gunungpw ok, let's redo this. Please change it to only one example with multiple maintainers. Keep in mind to keep names anonymous (John and Jane Smith maybe?).

**Comment by gunungpw** [comment]
Issue have been fix, Thank you 👍

**Review by Secrus — APPROVED** [review]

**Pull request merged**
