### PR TITLE
Backport caching improvements to 1.1 branch

### PR DESCRIPTION
**Pull request by maksbotan**
# Pull Request Check List

This backports #4618 #2398 to 1.1 branch to fix related issues.

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

I took liberty to skip updating tests.

### CODE REVIEW

**Comment by maksbotan** [comment]
CI seems to fail for reasons not related to my changes 🤔

**Comment by Secrus** [comment]
Hi. First of all, thank you for contributing to Poetry. However, since we are focusing on the 1.2 release, we won't be doing any more releases of version 1.1 (unless there are some breaking changes in 3rd party APIs like it was with 1.1.14). Backporting changes to an old version makes little sense since it probably will never be released.

**Comment by maksbotan** [comment]
Thanks for the response! I'll stick with poetry-core from my git branch at work for now, as this speedup is critical for us. Combined, my four pull requests drop `poetry lock --no-update` from 7 minutes to just 3 seconds.

What is the release schedule for 1.2 branch? And can you please review my PRs that add new improvements to master?

Thanks.

**Comment by neersighted** [comment]
> Thanks for the response! I'll stick with poetry-core from my git branch at work for now, as this speedup is critical for us. Combined, my four pull requests drop `poetry lock --no-update` from 7 minutes to just 3 seconds.
> 
> What is the release schedule for 1.2 branch? And can you please review my PRs that add new improvements to master?
> 
> Thanks.

https://github.com/python-poetry/poetry/issues/5586

We're working on catching up on reviews, but the last month has seen most of the team dealing with IRL priorities including health, work, and family -- we're still committed to getting this release out as soon as we are able, and to much smaller releases in the future to avoid similar pain.

**Comment by maksbotan** [comment]
Thanks! I've subscribed to that thread.

**Comment by Secrus** [comment]
I will close this to reduce noise in PRs

**Pull request closed without merging**
