### PR TITLE
mypy: fix missing return statement/value errors

### PR DESCRIPTION
**Pull request by jcmdln**
This commit fixes several `mypy` warnings about missing return statements, and return values missing a value. What this PR attempts to achieve is making poetry some amount more correct by improving type annotations or simply doing as `mypy` suggests.

The errors I addressed are as follows:

```sh
$ mypy poetry | grep "Missing return statement\|Return value expected"
poetry/utils/setup_reader.py:287: error: Missing return statement
poetry/utils/setup_reader.py:296: error: Return value expected
poetry/utils/setup_reader.py:300: error: Return value expected
poetry/utils/setup_reader.py:304: error: Return value expected
poetry/utils/setup_reader.py:307: error: Return value expected
poetry/utils/setup_reader.py:314: error: Return value expected
poetry/utils/setup_reader.py:324: error: Missing return statement
poetry/utils/setup_reader.py:337: error: Missing return statement
poetry/utils/setup_reader.py:353: error: Missing return statement
poetry/mixology/term.py:146: error: Return value expected
poetry/mixology/term.py:166: error: Return value expected
poetry/mixology/incompatibility.py:277: error: Return value expected
poetry/mixology/incompatibility.py:281: error: Return value expected
poetry/mixology/incompatibility.py:285: error: Return value expected
poetry/mixology/incompatibility.py:288: error: Return value expected
poetry/mixology/incompatibility.py:323: error: Return value expected
poetry/mixology/incompatibility.py:329: error: Return value expected
poetry/mixology/incompatibility.py:357: error: Return value expected
poetry/mixology/incompatibility.py:416: error: Return value expected
poetry/mixology/incompatibility.py:419: error: Return value expected
poetry/utils/password_manager.py:36: error: Return value expected
poetry/utils/env.py:961: error: Missing return statement
poetry/utils/env.py:966: error: Missing return statement
poetry/utils/env.py:1397: error: Missing return statement
poetry/utils/env.py:1403: error: Missing return statement
poetry/inspection/info.py:376: error: Missing return statement
poetry/inspection/info.py:403: error: Return value expected
poetry/inspection/info.py:433: error: Missing return statement
poetry/repositories/legacy_repository.py:144: error: Return value expected
poetry/repositories/legacy_repository.py:151: error: Return value expected
poetry/repositories/legacy_repository.py:397: error: Return value expected
poetry/repositories/legacy_repository.py:407: error: Return value expected
poetry/mixology/version_solver.py:157: error: Return value expected
poetry/mixology/version_solver.py:329: error: Return value expected
poetry/mixology/version_solver.py:451: error: Return value expected
poetry/mixology/version_solver.py:455: error: Return value expected
poetry/mixology/version_solver.py:458: error: Return value expected
poetry/console/commands/show.py:49: error: Missing return statement
poetry/console/commands/publish.py:44: error: Missing return statement
poetry/console/commands/init.py:70: error: Missing return statement
poetry/console/commands/init.py:525: error: Return value expected
poetry/console/commands/env/info.py:20: error: Missing return statement
poetry/console/commands/env/info.py:31: error: Return value expected
poetry/console/commands/cache/list.py:13: error: Missing return statement
poetry/console/commands/cache/clear.py:17: error: Missing return statement
poetry/console/commands/debug/resolve.py:38: error: Missing return statement
```

### CODE REVIEW

**Comment by jcmdln** [comment]
The errors referenced in https://github.com/python-poetry/poetry/pull/3801/checks?check_run_id=2136501677 are unrelated to my changes, but would you like for me to address those errors as part of this PR? Quickly skimming the most recent issues/PRs it doesn't appear that this work is already pending, and it would be easy enough to handle.

**Comment by jcmdln** [comment]
Ah, after a second glance those are my fault. I'll address them

**Comment by danieleades** [comment]
did you catch any i missed in #4024?

**Comment by neersighted** [comment]
This is stale now, but the good news is we've got working mypy via `pre-commit` in master. I'd suggest either rebasing and reducing the whitelist to cover modules that you have made pass mypy, or breaking this up into smaller PRs and submitting them individually.

**Comment by neersighted** [comment]
Actually, going to go ahead and close for now since @danieleades resolved a decent chunk of these. Please submit smaller PRs and help us shrink the whitelist!

**Pull request closed without merging**
