### PR TITLE
Fix `extras` hyperlink

### PR DESCRIPTION
**Pull request by m1so**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by m1so** [comment]
Hey @stephsamson, not sure what you mean exactly. 

It seems like other pages use the same url structure when linking across sections. For example: https://github.com/sdispater/poetry/blob/master/docs/docs/configuration.md#L3

Additionally, https://poetry.eustace.io/docs/pyproject/#extras seems to work just fine in the browser.

Please let me know if I missed something

**Comment by stephsamson** [comment]
Hey @m1so thanks for the quick response! You're right that it's the structure in the other sections but it looks to be breaking on the GitHub docs page too when you click on the link from that page [see here](https://github.com/sdispater/poetry/blob/master/docs/cli/#config).

Yes, that link works fine in the browser but the problem is the linking in the GitHub docs page. Ideally, neither would be breaking :(

**Comment by m1so** [comment]
Oh I see... could maybe the docs folder be moved one level down, placing the `mkdocs.yml` to the root of the repo and moving the theme folder to possibly `/assets`?

Not really sure how the aforementioned placement would affect building the docs as I couldn't find any related commands in the Makefile. 

Another solution might be changing https://www.mkdocs.org/user-guide/configuration/#docs_dir to `.` instead of the default `docs` and subsequently removing the `/docs/docs` directory.

**Review by mvoitko — APPROVED** [review]

**Comment by finswimmer** [comment]
It looks like this is fixed in the meantime.

Thanks a lot for your contribution anyway :+1:

**Pull request closed without merging**
