### PR TITLE
Console tests

### PR DESCRIPTION
**Pull request by DustinMoriarty**
# Pull Request Check List

Resolves: #3281 

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

Added basic tests for CLI commands poetry new and poetry update.

### CODE REVIEW

**Comment by DustinMoriarty** [comment]
@neersighted : This one did have merge conflicts. However, I resolved them by removing the proposed test_new.py. It looks like someone else already took care of adding a test for the new command.  Now this PR only covers adding a test for update. Can you please approve the workflow to run? Thank you.

**Comment by DustinMoriarty** [comment]
> @neersighted : This one did have merge conflicts. However, I resolved them by removing the proposed test_new.py. It looks like someone else already took care of adding a test for the new command. Now this PR only covers adding a test for update. Can you please approve the workflow to run? Thank you.

Nevermind. I thought I had tested this one. Looks like it fails now. I will get it fixed and push again tonight.

**Comment by DustinMoriarty** [comment]
@neersighted All set for review and merge now.

**Comment by Secrus** [comment]
@DustinMoriarty could you please merge changes from master and update your PR? That would allow for re-review

**Comment by Secrus** [comment]
Closing. No updates for a long time.

**Pull request closed without merging**
