### PR TITLE
Fix git clone test on non-English locale

### PR DESCRIPTION
**Pull request by kkhramova**
# Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

-----
When running tests using a non-English locale `vcs.git.test_system.TestSystemGit` test fails because git uses localized messages in its output.  

To reproduce run:

```sh
LANG=uk_UA.UTF-8 poetry run pytest
```

This PR fixes the issue by ignoring any output from git commands.

### CODE REVIEW

**Comment by dimbleby** [comment]
IMO it doesnt make a lot of sense for `SystemGit.run()` (and `.clone()` and `.checkout()`) to return strings.

Suggest that it would be preferable to use `subprocess.check_call()` - sending stdout to devnull - instead of `subprocess.check_output()`, then the locale is of no interest to anyone.

**Comment by kkhramova** [comment]
I made the changes, @dimbleby. 
Can you please take another look?

**Comment by dimbleby** [comment]
> Suggest that it would be preferable to use subprocess.check_call() - sending stdout to devnull - instead of subprocess.check_output()

**Comment by kkhramova** [comment]
Thank you, @dimbleby 
Now subprocess.check_output() is changed to subprocess.check_call()

**Comment by dimbleby** [comment]
and how about redirecting stdout?  does the code as written write the output to the terminal?

**Comment by kkhramova** [comment]
stdout is now redirected to devnull.
@dimbleby thank you for your patient guidance.

**Review by radoering — APPROVED** [review]

**Pull request merged**
