### PR TITLE
Remove non-existing --path option, add missing options

### PR DESCRIPTION
**Pull request by fredrikaverpil**
I can't see this option in `poetry add --help` and I've also tried to actually run the command `poetry add --path $PATH` and I get this:

```python
clikit.api.args.exceptions.NoSuchOptionException: The "--path" option does not exist.
```

I verified the above with both version 1.1.4 as well as latest master commit https://github.com/python-poetry/poetry/commit/2aab9bcd495e11e5f4491aa72a9510773cc4a90e.

### CODE REVIEW

**Review by finswimmer — CHANGES_REQUESTED** [review]
Thanks a lot for this change  @fredrikaverpil .

I've noticed that this section is missing some of the options described in `poetry add --help`. Could you please add those?

fin swimmer

**Comment by fredrikaverpil** [comment]
> Thanks a lot for this change @fredrikaverpil .
> 
> I've noticed that this section is missing some of the options described in `poetry add --help`. Could you please add those?

@finswimmer sure, have a look now. Maybe the title of this PR should be updated...

**Review by finswimmer — CHANGES_REQUESTED** [review]

**Comment by fredrikaverpil** [comment]
@finswimmer 👍

**Review by finswimmer — APPROVED** [review]
Thanks a lot @fredrikaverpil :+1:

**Pull request merged**
