### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by sdispater**
## Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

This PR changes the user interface a bit to make it more intuitive. It changes colors in some places to be more readable and provide a consistent interface on dark and light terminal themes.

It also upgrades Cleo and CliKit to provide beautiful and more intuitive errors with various levels of detail depending on the current verbosity. The rendered stack traces will also collapse duplicated frames (useful for recursion errors).

Here are some examples:

**Verbose mode**

Screenshot 2020-03-25 at 19 49 43

**Debug mode**

Screenshot 2020-03-25 at 19 51 08

**Duplicated frames**

Screenshot 2020-03-25 at 19 58 08

### CODE REVIEW

**Comment by JBKahn** [comment]
Where can I find the `woops` source code repository?

**Comment by SanketDG** [comment]
https://pypi.org/project/woops/

**Comment by JBKahn** [comment]
We can download and read it but I was hoping it was in a public repo for convenience.

**Comment by abitrolly** [comment]
I must admit this part of `poetry` is my favourite.

**Pull request merged**
