### PR TITLE
WIP - Plugin system

### PR DESCRIPTION
**Pull request by sdispater**
## Pull Request Check List

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

This is a WIP implementation of the previously mentionned plugin system. It is not fully functional at the moment (and does not work at all with the recommended installer). The implementation will likely change as I make progress on it. Nonetheless, the general idea of what it will look like is here.

Note that it will likely not make it to the `1.0.0` release.

### CODE REVIEW

**Comment by kapilt** [comment]
one comment, its a little unclear if this is present already, but I was wondering about ensuring that builtin commands can't be overridden to avoid inconsistencies in user experience.

**Comment by keattang** [comment]
Eagerly awaiting this! Any ideas when it may get released?

**Comment by danieleades** [comment]
This seems like a really powerful and flexible plugin system. I'm looking to seeing how people extend poetry's functionality using this framework to make it a powerful test runner and CI tool.

I also wonder if this is not quite heavy weight for the many people who are looking for a simple hook. Consider `Yarn`'s hook system where scripts definesdin the project manifest with 'special' names are invoked for specific methods. For example if you have a script defined called 'prepublish', that script will be called before publishing.

How can I use this plugin to create a simple hook at a specific point? My use-case, for example, is to run code-generation on some proto files. Creating an entire package to run a one line script seems excessive.

**Comment by sdispater** [comment]
Closing in favor of #3733

**Pull request closed without merging**
