### PR TITLE
fix(constraints): Pass along pre-release in all cases

### LINKED ISSUE #1150: Pre-release `~=` constrains are mis calculated
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows
- **Poetry version**: 0.12.16
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A, requires access to a proprietary pypi instance

## Issue

My constraints aren't resolving.

A rough look at my dependency tree
- A: `B = "^0.7.5" via poetry
- B: `"C~=0.2.0dev16"` via setup.py

Poetry complains that it cannot resolve B's dependency on C
```
[SolverProblemError]
Because B (0.7.5) depends on C(>=0.2.0,<0.3.0) which doesn't match any versions, B is forbidden.
So, because no versions of B match >0.7.5,<0.8.0
 and A depends on B (^0.7.5), version solving failed.
```

I traced the problem down into [`semver/__init__.py:parse_single_constraint`](https://github.com/sdispater/poetry/blob/master/poetry/semver/__init__.py#L67) where the constraint
- `~=0.2.0dev16`
gets compiled into
- `>=0.2.0,<0.3.0`

In contrast, the constraint
- `~=2.0.dev0`
correctly gets compiled into
- ` >=2.0.dev0,<3.0.0`

The problem seems to be
```python
        if precision == 2:
            low = version
            high = version.stable.next_major
        else:
            low = Version(version.major, version.minor, 0)
            high = version.stable.next_minor
```
where if the `precision` is 1 or 3, then the pre-release is dropped from `low`, disqualifying them from resolving the constraint.

### PR DESCRIPTION
**Pull request by epage**
Fixes #1150

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [X] ~~Updated **documentation** for changed code.~~ N/A

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by epage** [comment]
I didn't see direct tests for this function so I was unsure what is the appropriate way of testing it.

**Comment by epage** [comment]
Tests are now added

**Comment by epage** [comment]
@drunkwcodes could you clarify your thumbs down?

**Comment by drunkwcodes** [comment]
It's a non-issue because of the occurence of #1153.

**Comment by epage** [comment]
So while part of the problem was fixed in #1481, this problem still exists while this PR has been getting no attention from the maintainers.  Do I bother resolving the conflicts or do I let the rudely applied bots close this?

**Comment by finswimmer** [comment]
Hey @epage,

> So while part of the problem was fixed in #1481, this problem still exists [...]

could you please add some more details about what problem still exists?

Thanks a lot!

fin swimmer

**Comment by epage** [comment]
> could you please add some more details about what problem still exists?

#1481 claimed to fix `~=` but missed the case covered here: pre-release constraints.

**Comment by abn** [comment]
The relevant code in this PR has moved to poetry-core. This change, if still required, should be opened there.

**Pull request closed without merging**
