### PR TITLE
Support non SHA256/SHA384/SHA512 HTTPRepository

### PR DESCRIPTION
**Pull request by gaborbernat**
Resolves https://github.com/python-poetry/poetry/issues/6301

### CODE REVIEW

**Comment by gaborbernat** [comment]
@radoering would appreciate if you could take a look here 😊 thanks!

**Comment by avicennax** [comment]
Would it be naive to assume we can easily update / rename this function and leverage `hashlib.md5` with a hash name check?

**Comment by radoering** [comment]
> @radoering would appreciate if you could take a look here 😊 thanks!

LGTM. IMO, after adding a test in `test_chooser.py`, it could be merged.

> Would it be naive to assume we can easily update / rename this function and also support md5 via hashlib.md5 with a hash name check?

See https://github.com/python-poetry/poetry/issues/6301#issuecomment-1604555396

**Comment by gaborbernat** [comment]
@radoering all done now 👍

**Review by radoering — APPROVED** [review]

**Comment by gaborbernat** [comment]
@radoering could we get a release cut for this? Thanks!

**Comment by radoering** [comment]
I don't think I'll find the time within the next weeks. Thus, probably not before August.

**Comment by radoering** [comment]
Unfortunately, I can't. You can track the progress in #8232. I'll skim the issues for blockers, review some PRs and wait for some reviews for myself over the next few weeks and afterwards start preparing the release. Thus, my estimation is still August.

**Comment by threat0day** [comment]
@radoering  OK thanks)

**Pull request merged**
