### PR TITLE
Fix AttributeError on hash mismatch

### PR DESCRIPTION
**Pull request by paulmelnikow**
This replaces the AttributeError reported in #4085 with the proper exception.

# Pull Request Check List

Resolves: N/A (related to #4085, however the underlying error is not fixed)

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
I'm seeing these test failures locally too, though they do not seem to be related to the changes in this PR.

**Comment by paulmelnikow** [comment]
@finswimmer Could I ask you to take a look at this?

If you think a test is needed to merge it, I'd appreciate some guidance on that. If there is some existing coverage of these code paths I'm happy to add some tests of the error case. Though if not I'm probably not quite ready to create tests in an area of the code where there's no test coverage now. In any case if you feel that's needed, would appreciate pointers on where to start! Thanks!

**Comment by sdispater** [comment]
@paulmelnikow Thanks for the fix!

Could you rebase your PR on the the latest version of the `master` branch?

**Comment by paulmelnikow** [comment]
@sdispater Thanks for reviewing! Done!

**Comment by paulmelnikow** [comment]
I thought I had reduced complexity for Sonar but it looks like not.

I imagine the way to fix this is to break out a helper method from this one. Perhaps lines 655-671 could become a new method? If you agree, could you suggest what that method should be called?

**Comment by paulmelnikow** [comment]
> I imagine the way to fix this is to break out a helper method from this one. Perhaps lines 655-671 could become a new method? If you agree, could you suggest what that method should be called?

@sdispater Could you offer any guidance on this? I took another look at how to refactor this to satisfy Sonar and it seems more like what's needed is not a second helper function, but to push some of this code complexity into a lower-level abstraction. But I'm happy to execute whatever refactor you suggest.

**Comment by paulmelnikow** [comment]
@sdispater gentle nudge

**Comment by paulmelnikow** [comment]
@sdispater I'd love to get this merged!

**Comment by neersighted** [comment]
> @sdispater I'd love to get this merged!

Sorry about the delays here -- does this still reproduce on master?

**Comment by neersighted** [comment]
Actually, it looks like #4531 fixed this and I already validated it does not reproduce. Please comment/re-open if that's not the case and we still need to get a fix in.

**Pull request closed without merging**
