### PR TITLE
Add option to install only dev dependencies (#2572)

### PR DESCRIPTION
**Pull request by opelr**
# Pull Request Check List

Resolves: #2572

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by TylerLubeck** [comment]
Hi! Is there anything I can do to help get this merged? It would be hugely helpful for me

**Review by finswimmer — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution @opelr. :+1: 

This one looks good to me. Can you please rebase onto master again, to force the tests to run again?

fin swimmer

**Review by finswimmer — CHANGES_REQUESTED** [review]
Thanks a lot for the quick rebase.

Just one more thing. At the moment the project itself get's installed at the end. I think we should disable this, just like one can do with the `--no-root` flag.

**Comment by opelr** [comment]
@finswimmer Sounds good! I updated my commit to reflect your request, let me know if that's what you had in mind.

**Review by finswimmer — APPROVED** [review]
Thanks a lot :rocket:

**Comment by TylerLubeck** [comment]
Thanks!! y'all are heros

**Comment by noamba** [comment]
Hi @opelr @finswimmer, this is a very useful feature for me, many thanks for getting it done. 
I don't think this feature is in release 1.1.5, I assume this will be released sometime in the future? Do you have an idea when? Thanks, Noam

**Comment by colbyhub** [comment]
@finswimmer it would be very helpful for our team to use this feature! Even if it was just in a preview release, our team could start taking advantage of this. Thank you for your work on this project! :muscle:

**Comment by jose-lpa** [comment]
I'm not sure this has been implemented as people expected it.

I understood from all related issues and PRs that people wanted the same as I actually want: be able to install the development dependencies, **but without altering the main dependencies status**.

What this actually does, as far as I can see, is to make sure that **only the development dependencies are installed**. So it actually **removes any other dependency not specified as `dev`**.

Quick check screenshot:

Screenshot from 2021-06-29 16-16-18

So as you can see the command `poetry install --dev-only` actually left the project unusable, because it removed all core packages just by not being specified as `dev` dependencies.

I'm not sure what people wanted, but I seriously doubt anyone would expect this behavior when issuing a command to "install development dependencies". 

In my case, what I wanted is to use `poetry install --no-dev` in a Dockerfile to build a container image that can be used in both development, CI and Production. Then use `poetry install --dev-only` in the CI scripts as a previous step before running tests.

**Pull request merged**
