### PR TITLE
Fix handling of forward slashes and url encoding in credentials

### PR DESCRIPTION
**Pull request by lubert**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://python-poetry.org/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

## Problem
- Credentials containing `/` do not urlencode it, since `quote()` passes the `safe='/'` by default 

## Solution
- Pass `safe=''` so that `/` is encoded properly

### CODE REVIEW

**Comment by lubert** [comment]
Hi @k4nar, I had the issue with Python 3.7.1.

The documentation for 2 and 3 list `safe='/'` as a default argument, which I believe is why `/` isn't encoded.
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote
https://docs.python.org/2/library/urllib.html#urllib.quote
Though I do see `quote_via` as a param for `urlencode`

That's a fair point about genuine creds containing a urlencoded string, I was trying to solve for an already encoded password passed via env, which is what we have at work in our build pipeline and is nice for `pip` since it doesn't do any encoding/unencoding.
I'll update the PR, since we can always decode before passing it to `poetry config`.

**Comment by k4nar** [comment]
Ah yes, sorry, I was reading the doc of `urlencode` instead of `quote` :) .

**Comment by lubert** [comment]
@sdispater, any chance of getting this merged into the next release?

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
