### PR TITLE
Fix a race condition in simultaneous poetry installations updating the cache

### PR DESCRIPTION
**Pull request by zweger**
If one poetry installation is writing to the cache while a second installer is attempting to read that cache file, the second installation will fail because the in-flight cache file is invalid while it is still being written to by the first process. 

This PR resolves this issue by having Poetry write to a temporary file in the cache directory first, and then rename the file after it's written, which is ~atomic.

# Pull Request Check List

Resolves: #5142 

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

I'm not sure how to test this change, as the conditions which cause this bug to appear are a little hard to reproduce.

### CODE REVIEW

**Comment by radoering** [comment]
Makes sense to me. I just wonder if it's wise to import a helper function from `requests.utils`. It's probably not part of the public API, is it? Maybe, we should add "our own" `atomic_open()` (to `poetry.utils.helpers` maybe)?

I don't know how to test this either. Maybe, we can go without a test here.

@neersighted What do you think?

**Comment by neersighted** [comment]
I'm wondering if #6471 is the better solution -- I agree that we should yoink `atomic_open` into this repo (with a comment for attribution/licensing) if we go forward with this. However, as either would likely be part of 1.3 exclusively, I think making the OS work for us instead of against us is the better long-term path forward.

**Comment by dimbleby** [comment]
#6471 and this are independent fixes, it would make perfect sense to merge them both

(#6471 relates to files owned by cachecontrol's filecache, this one relates to a file written to by poetry regardless of whether caching is enabled or not)

**Comment by neersighted** [comment]
Fair enough, and good point

**Comment by zweger** [comment]
Hi, thanks for the feedback. I've updated this PR to include `atomic_open` in `poetry.utils.helpers`. Regarding testing, I will note that while poetry doesn't have a test for this particular situation (concurrent installations / ctrl+c during install), poetry's current tests do at least cover this code.

**Review by neersighted — APPROVED** [review]

**Pull request merged**
