### PR TITLE
fix(repositories): use `urls` for versioned JSON API instead of `releases`

### PR DESCRIPTION
**Pull request by mkniewallner**
# Pull Request Check List

Resolves: #5967 
Resolves: #5970 

- [x] Added **tests** for changed code.
- [ ] ~Updated **documentation** for changed code.~ Not applicable

When retrieving package metadata for a specific version from `pypi.org` JSON API, Poetry currently relies on a `releases` keys to look for the correct version based on the URL.
Following https://github.com/pypi/warehouse/pull/11775, `releases` has been removed from `/pypi/<package_name>/<version>/json` endpoints, so Poetry can't pick up this metadata anymore.

There's no real reason to use `releases`, since `urls` is also available, and has the advantage of directly returning the version we are looking for (so instead of checking for `data["releases"][version]`, we directly access the version we are looking for in `data["urls"]`).

Note: Given that this makes Poetry locking mechanism broken on all released versions (not only on `master`), this would probably require a backport to the `1.1` branch, even if it is mostly unmainted. Started 
https://github.com/mkniewallner/poetry/commits/fix/fix-releases-key-pypi-repository-1.1 for that.

### CODE REVIEW

**Comment by mkniewallner** [comment]
Tests pass, which means we definitely lack some test coverage for this.

**Comment by finswimmer** [comment]
> Tests pass (minus the flaky 3.11-dev on macOS), which means we definitely lack some test coverage for this.

I think the `test_package` test in `test_pypi_repository.py` is a good candidate for extending the test. We have to check for the content of the `files`  attribute.

**Comment by mkniewallner** [comment]
> Probably the json files under `tests/repositories/fixtures/pypi.org/json` must be adopted.

Agree, though `releases` is also used in https://github.com/python-poetry/poetry/blob/584aaee5f8da9f950f98d1ef0ebc06fe835e5d96/src/poetry/repositories/pypi_repository.py#L66
So we will probably need to change that too.

**Comment by dimbleby** [comment]
> will probably need to change that too.

I don't think so - I think that is looking at the reponse from the non-versioned page, which continues to include this information

**Comment by mkniewallner** [comment]
> I don't think so - I think that is looking at the reponse from the non-versioned page, which continues to include this information

Oh yeah, https://github.com/pypi/warehouse/pull/11775/files#diff-beb4788f749d9d561005b6542d39b9f7d6f0ed2e7e9bd8b614673294aab9b488R188-R189 you're right indeed, `/pypi/<project_name>/json` is untouched, my bad for overlooking that.

**Comment by mkniewallner** [comment]
Updated the PR to:
- add a dedicated version fixture for `requests` in https://github.com/python-poetry/poetry/pull/5972/commits/9f29869d7377086015e1348af766962ebe6d7d66 (so it uses this file instead of [the global one](https://github.com/python-poetry/poetry/blob/9cf87a285a2d3fbb0b9fa621997b3acc3631ed24/tests/repositories/fixtures/pypi.org/json/requests.json), according to [this code](https://github.com/python-poetry/poetry/blob/9f29869d7377086015e1348af766962ebe6d7d66/tests/repositories/test_pypi_repository.py#L45-L50))
- remove all `releases` key from the versioned fixtures in https://github.com/python-poetry/poetry/pull/5972/commits/6b40ebc59761f19be95d14126ef4639ab236ec18

**Review by finswimmer — APPROVED** [review]
LGTM and also tested this locally :medal_sports: :rocket: 

Can you please prepare a backport to 1.1?

**Comment by mkniewallner** [comment]
> Can you please prepare a backport to 1.1?

Yes, PR is https://github.com/python-poetry/poetry/pull/5973, just waiting for CI to pass.

**Comment by mbelang** [comment]
Updated to 1.1.14 and still doing it. Is there something to modify to actually fix the issue locally?

**Comment by mkniewallner** [comment]
> Updated to 1.1.14 and still doing it. Is there something to modify to actually fix the issue locally?

Yes, you have to clear Poetry's cache first:
```bash
poetry cache clear pypi --all
```

**Comment by mbelang** [comment]
Yeah it works thx. I found the answer in one of the issues.

**Comment by dwangfaulkner-fn** [comment]
Sorry to jump onto this thread but is there anywhere to see when a new beta release will be cut with this very critical fix? We'd prefer to use a released version instead of building from main, as I'm sure many other folks would.

**Comment by mkniewallner** [comment]
> Sorry to jump onto this thread but is there anywhere to see when a new beta release will be cut with this very critical fix? We'd prefer to use a released version instead of building from main, as I'm sure many other folks would.

A new beta for `1.2` has been released: https://github.com/python-poetry/poetry/releases/tag/1.2.0b3.

**Pull request merged**
