### PR TITLE
fix: Pass in source_subdirectory to get_package_from_vcs

### LINKED ISSUE #5521: poetry add of a GitHub repo with subdirectory fails
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: NixOS unstable
- **Poetry version**: latest master as of https://github.com/python-poetry/poetry/commit/6721ebe0f0c201d50862e8d37ed2c6bfaa03d190

## Issue
I am aware that the Git subdirectory feature was merged in [#192](https://github.com/python-poetry/poetry-core/pull/192). I have also read #755. My goal is to install this [repo](https://github.com/zulip/talon/tree/talon-core-split/talon-core).
This is the syntax that works in requirements.txt (but I want to convert it to Poetry):
```
https://github.com/zulip/talon/archive/1711705c952806d4a704c7dbf58f21db8e11756a.zip#egg=talon-core==1.4.8.zulip1&subdirectory=talon-core
```

I have tried adding this to my pyproject.toml:
```
talon-core = {git = "https://github.com/zulip/talon.git", rev = "1711705c952806d4a704c7dbf58f21db8e11756a", subdirectory = "talon-core" }
```
then ran `poetry lock --no-update` but this fails with
```
  PackageInfoError

  Unable to determine package info for path: /tmp/pypoetry-git-talonlh1f69va
  
  Command ['/tmp/tmp9vi34lbc/.venv/bin/python', '-'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "<stdin>", line 9, in <module>
    File "/tmp/tmp9vi34lbc/.venv/lib/python3.10/site-packages/build/__init__.py", line 208, in __init__
      _validate_source_directory(srcdir)
    File "/tmp/tmp9vi34lbc/.venv/lib/python3.10/site-packages/build/__init__.py", line 109, in _validate_source_directory
      raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
  build.BuildException: Source /tmp/pypoetry-git-talonlh1f69va does not appear to be a Python project: no pyproject.toml or setup.py
```
This is because it looks like the subdirectory is not passed to `build.ProjectBuilder`. I checked the content of /tmp/pypoetry-git-talonlh1f69va, and it actually the root of the repo, not the subdirectory (the one that actually has setup.py).

Then, I tried `poetry add -v 'git+https://github.com/zulip/talon.git#1711705c952806d4a704c7dbf58f21db8e11756a&subdirectory=talon-core'`. I got an identical error message.

### PR DESCRIPTION
**Pull request by rht**
Fixes #5521.
With this commit, one can finally add a Git dependency with a
subdirectory, e.g.

```
talon-core = {git = "https://github.com/zulip/talon.git", rev = "1711705c952806d4a704c7dbf58f21db8e11756a", subdirectory = "talon-core" }
```

# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code. N/A because the subdirectory is not yet documented

### CODE REVIEW

**Comment by rht** [comment]
cc @sdispater

**Comment by rht** [comment]
Note: while with this patch, the command `poetry lock` works, and it checks out the Git subdirectory, it still does not write the metadata to poetry.lock.

**Comment by andersk** [comment]
If I understand correctly, this is addressed more completely by #5172.

**Comment by andersk** [comment]
A patch equivalent to this one was merged today as part of #5648 (although #5172 still has further fixes that are still needed).

**Comment by neersighted** [comment]
Closing this due to a lack of tests and equivalent/tested work in #5172

**Pull request closed without merging**
