### PR TITLE
--global-options Issue #845 Candidate

### PR DESCRIPTION
**Pull request by reedjosh**
# Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

Regarding:
**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` 

If the methods used in this pull request are satisfactory, I will rebase upon the develop branch.

I added an argument to the add command and updated through to the schema and pip install.

I've personally used this code to install a package that wouldn't be possible otherwise. I added a test in the add command and ran the pre-commit hook.

I have not full addressed issue #845 as I did not provide --build-options or --install-options. If these are desired I can add them too, I just wanted to get feedback on my methods first.

Thank you!

### CODE REVIEW

**Comment by reedjosh** [comment]
Tests all fixed up. Please let me know your thoughts. I'm not certain the class usage model I've used jives with the intent of the objects. It does generate a nice readable toml file though.

pyodbc = {version = "4.0.26", global-options = ["build_ext", "--include-dirs", ".../joshuare/pkgs/include"]}

**Comment by clintlombard** [comment]
This would be super useful, for example installing [tensorflow-graphics](https://github.com/tensorflow/graphics) with GPU support requires passing a flag during installation. This fix would make it as simple as:

```
[tool.poetry.dependencies]
...
tensorflow-graphics-gpu = { git = "ssh://git@github.com:tensorflow/graphics.git", branch="master", global-option="--compute_platform gpu"
```

**Comment by reedjosh** [comment]
@clintlombard  Yup, we've been keeping a local copy of this branch at work until it gets merged. Haven't heard anything from the maintainers though. : / 

I'm still happy to work this further once I do hear back.

**Comment by thrix** [comment]
> I have not full addressed issue #845 as I did not provide --build-options or --install-options. If these are desired I can add them too, I just wanted to get feedback on my methods first.

Including them would be awesome, we now have to manually workaround this common problem on Fedora:
```
pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
```
by manually reinstallaing the package in venv

**Comment by reedjosh** [comment]
@finswimmer Hey, I see people are still asking for this feature. Just bumping to see if you have time to review.

Thank you!

**Comment by jkklapp** [comment]
This PR needs to be merged in 🙏

**Comment by mvtm-dn** [comment]
I apologize, but does anybody work to merge this request?

**Comment by gjoseph92** [comment]
@reedjosh if this ever does get reviewed, here's a vote for `--install-options`; it would help me a lot. And here's a bump hoping this does get reviewed someday.

**Comment by ali5h** [comment]
another bump

**Comment by p-i-** [comment]
> Including them would be awesome, we now have to manually workaround this common problem on Fedora:
> 
> ```
> pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
> ```
> 
> by manually reinstallaing the package in venv

Bump! Are we nearly there yet? 🙈

**Comment by phyrwork** [comment]
Bumpity bump. What's left to be done here?

**Comment by mvtm-dn** [comment]
Bump

**Comment by neersighted** [comment]
Closing as pip is very much an internal implementation detail of Poetry these days, and we are moving to a custom installer and will drop our dependence on pip.

**Comment by dbischof90** [comment]
> Closing as pip is very much an internal implementation detail of Poetry these days, and we are moving to a custom installer and will drop our dependence on pip.

As an addendum to this, do you have tracking issues for the development of the internal custom installer?

**Comment by neersighted** [comment]
https://github.com/python-poetry/poetry/pull/6205

**Pull request closed without merging**
