### PR TITLE
Emit export errors to stderr to prevent invalid output

### PR DESCRIPTION
**Pull request by colindean**
An error in export could emit error messages to stdout, causing the requirements.txt output to stdout to be invalid.

# Pull Request Check List

Resolves: #4109

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

N.b. I made this change in GitHub so I did not run tests or add tests to ensure the bad behavior doesn't happen.

### CODE REVIEW

**Review by finswimmer — APPROVED** [review]
Thanks a lot :+1:

**Review by finswimmer — CHANGES_REQUESTED** [review]
Some tests are failing in `tests/console/commands/test_export.py` because the output is checked in stdout.

So you have to change `tester.io.fetch_output()` to `tester.io.fetch_error()` where needed.

**Comment by colindean** [comment]
Fixed! I noted that when I ran tests with `poetry run pytest tests/`, they all pass, but when I run with `make test`, nearly all tests fail. This happens on `master` branch, too.

**Comment by jleclanche** [comment]
@finswimmer This is a simple one, good to merge? Your requested change has been addressed, the remaining test failure looks unrelated ("connection reset by peer")

**Comment by finswimmer** [comment]
@colindean: Could you please rebase your branch, to force the checks to run again?

**Comment by colindean** [comment]
Checks are running now!

**Review by finswimmer — APPROVED** [review]

**Pull request merged**
