### PR TITLE
Prepare tests for Python 3.12 PyPI trove classifier

### PR DESCRIPTION
**Pull request by jakob-keller**
# Pull Request Check List

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

https://github.com/python-poetry/poetry-core/pull/631 adresses #8375, but currently fails poetry downstream tests.

This PR prepares poetry unit tests for https://github.com/python-poetry/poetry-core/pull/631.

### CODE REVIEW

**Comment by jakob-keller** [comment]
Tests are expected to fail. This PR is intended to work in conjuncture with https://github.com/python-poetry/poetry-core/pull/631.

**Comment by radoering** [comment]
I tend to think that we should make these tests more generic so we avoid the dance for each new Python version:
We could change the expectation in the tests to all Python versions in `Package.AVAILABLE_PYTHONS` that are allowed by the test's Python constraint.

**Comment by jakob-keller** [comment]
> I tend to think that we should make these tests more generic so we avoid the dance for each new Python version:
> We could change the expectation in the tests to all Python versions in `Package.AVAILABLE_PYTHONS` that are allowed by the test's Python constraint.

You're absolutely right. I'll try to address that tonight.

**Comment by jakob-keller** [comment]
Superseded by #8397

**Pull request closed without merging**
