### PR TITLE
docs/configuration: fix note markdown

### PR DESCRIPTION
**Pull request by Cireo**
This repairs a broken triple-bang note.  Also cleans up a few stray
double-newlines and very long lines to match rest of file.

### CODE REVIEW

**Comment by Cireo** [comment]
There is a one-letter typo in cli as well, happy to lump that with this or open a new one.

> always set the develop attribute explicit, to make

**Comment by Cireo** [comment]
Ping

**Comment by Cireo** [comment]
Pong

**Review by justinmayer — APPROVED** [review]
Nice catch, @Cireo. This looks good to me. 👍

**Review by abn — APPROVED** [review]

**Pull request merged**
