### PR TITLE
Allow to specify source url in global pip config

### PR DESCRIPTION
**Pull request by LittleboyHarry**
# Pull Request Check List

Resolves: #1632 #559 #664

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

Let poetry resolve pip config `global.index-url` as default pypi repository if exists.

### CODE REVIEW

**Comment by LittleboyHarry** [comment]
Auto merge review check bot fails because some old code in this file don't fit `black` format style.

**Comment by sdispater** [comment]
Thanks for your contribution!

However, I do not feel comfortable using information coming from other tools automatically. This should be done explicitly by the user.

**Comment by LittleboyHarry** [comment]
Hope there will be one way to specify **custom default pip repository in poetry global config** in the new version.

**Comment by DanielW10001** [comment]
@sdispater How about promoting the user to ask whether to use the `global.index-url` from pip config when it presents?

**Comment by swist** [comment]
This feature would be very useful for scenarios where jwt for authenticating with the registry is prepended to the beginning of the repo url, AWS codebuild for example builds repo urls like so:
```
https://aws:<JWT>@<domain>-<aws-account>.d.codeartifact.eu-west-1.amazonaws.com/pypi/python/simple/
```
Current setup that requires poetry users to define this as a static url inside of `pyproject.tml` makes it impossible to use (because these are sessioned to ~12hours, JWT gets re-rolled afterwards)

**Pull request closed without merging**
