### PR TITLE
refactor(test_env, conftest): move default venv flags to fixture

### PR DESCRIPTION
**Pull request by vlad0337187**
# Pull Request Check List

Resolves: [suggestion to make code more clear in merged PR](https://github.com/python-poetry/poetry/pull/3711#discussion_r592834456)

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by vlad0337187** [comment]
@abn , hello, did a little refactor, hope, that's what you wanted in you comment.
Could you review please when you'll have some time ?

Thanks.

Failing stages aren't related to current changes.

**Review by abn — CHANGES_REQUESTED** [review]
LGTM. Thanks @vlad0337187. Can you do a rebase on master please? That should resovle the failures I reckon.

**Comment by vlad0337187** [comment]
@abn , rebased, seems now all is good.

**Comment by neersighted** [comment]
Rebased, but still broken thanks to a broken `master`. Will circle back once the master branch is fixed.

**Comment by Secrus** [comment]
pre-commit.ci autofix

**Review by Secrus — APPROVED** [review]

**Pull request merged**
