### PR TITLE
Conda also has a dependency resolver in Python. Resolves: #477.

### LINKED ISSUE #477: Conda has a good solver to properly resolve dependencies in Python (and any other language ecosystem)
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

The documentation states:

> And, finally, there is no reliable tool to properly resolve dependencies in Python.

This in untrue, conda has used a good solver for years now. Please update this.

### PR DESCRIPTION
**Pull request by stephsamson**
- [x] Updated **documentation** for changed code.

Fixes #477.

### CODE REVIEW

**Comment by sdispater** [comment]
I wonder if we could rephrase it. The idea behind my original sentence is that there is currently no resolver that can resolve dependencies properly for PyPI and custom indices. Conda has a resolver but only works with conda forge and similar, but I might be wrong.

**Comment by cjw296** [comment]
Conda's resolver also ends up having some real performance problems in certain circumstances:
https://github.com/conda/conda/issues/7239

**Comment by Conan-Kudo** [comment]
The new mamba resolver is likely to resolve these issues: https://github.com/QuantStack/mamba

**Comment by abn** [comment]
@stephsamson can we do a rebase of this so the new checks are triggerred?

**Comment by stephsamson** [comment]
@abn done ✅

**Review by abn — APPROVED** [review]

**Pull request merged**
