### PR TITLE
add git+http scheme.

### PR DESCRIPTION
**Pull request by gitnutz**
# Pull Request Check List

Resolves: #6982

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by dimbleby** [comment]
cf #6619

**Review by neersighted — CHANGES_REQUESTED** [review]
Happy to merge this if you alter it according to the review feedback in #6619.

**Comment by neersighted** [comment]
Hi @gitnutz, I see you're still updating this PR. It's not mergable as is -- are you planning to address the review feedback, or should we close it in favor of the existing PR also in this area?

**Comment by Secrus** [comment]
Closing in favor of #6619

**Pull request closed without merging**
