### PR TITLE
Downloader support resume from connection reset

### PR DESCRIPTION
**Pull request by austinzh**
# Pull Request Check List

Resolves: #3219
Resolves: #9551

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Review by radoering — CHANGES_REQUESTED** [review]
`download_file()` is used in some more places (`HTTPRepository`, `DirectOrigin`), which might not be relevant for installing but only for locking. Maybe, connection resets are not that relevant for locking. On the other side, it feels more consistent to also retry in this case. What do you think?

`HTTPRepository` already has the config available, so it is easy to use the setting. For `DirectOrigin`, we had to add another parameter.

**Comment by austinzh** [comment]
> `download_file()` is used in some more places (`HTTPRepository`, `DirectOrigin`), which might not be relevant for installing but only for locking. Maybe, connection resets are not that relevant for locking. On the other side, it feels more consistent to also retry in this case. What do you think?
> 
> `HTTPRepository` already has the config available, so it is easy to use the setting. For `DirectOrigin`, we had to add another parameter.

Sure. I can add parameter to them, It's my first time working in this repo, I agree that even they are not much needed for retry it's better to make it all consistent.

**Comment by radoering** [comment]
> But for the config, should we still use `installer.max-retries`? I think it's still valid name right? Or we add `solver.max-retries` ?

Good question. Thinking about it, `installer.max-retries` might have been a bit ambiguous from the start: We only retry the download not the complete installation. I think we should introduce a new section, maybe call it `network` or `requests`? (We already have a [`POETRY_REQUESTS_TIMEOUT`](https://python-poetry.org/docs/faq/#my-requests-are-timing-out), which is not yet available via config but only via environment variable; anyway, I think that one would fit into the same section.)

**Review by austinzh — COMMENTED** [review]
Change config to "requests.max-retries"

**Comment by SmartManoj** [comment]
Please reopen https://github.com/python-poetry/poetry/issues/3219 to close the duplicate of #9551

**Comment by radoering** [comment]
> Please reopen #3219 to close the duplicate of #9551

I do not think reopening #3219 makes sense because it is was closed a long time ago. Generally, we do not need an issue if we already have a PR. However, since some users only search issues, I think it is ok to keep #9551 open until this one is merged.

**Comment by radoering** [comment]
> Does this PR need any change?

I think all my comments have been addressed but I still have to review the changes. I won't have time for the next two weeks but feel free to remind me end of August if I have not come back to this issue by then.

**Review by radoering — APPROVED** [review]

**Pull request merged**
