### PR TITLE
WIP: Official Docker images

### PR DESCRIPTION
**Pull request by lorantalas**
# Pull Request Check List

Resolves: #4036

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

Using structure from python official image. 

WIP

### CODE REVIEW

**Comment by neersighted** [comment]
Hey @lorantalas, thanks for working on this. I was considering doing the same but haven't gotten around it it. Could you join the Discord server to discuss your PR? This is a fairly large amount of code/an additional maintenance burden for a team that's already spread thin, so I want to make sure we think about what we're committing to support carefully before a merge.

**Comment by lorantalas** [comment]
@neersighted Yes. Sure, let's discuss it. I joined the discord server. Feel free to ping me. `lorantalas#3910`

**Comment by neersighted** [comment]
Closing for now as per Discord discussion we're not going to be merging these files into the main repo. However, we are interested in potentially hosting them experimentally in the Github org (as part of their own repo), with their own sub-team, and even considering working on inclusion in the Docker Official Images collection ala-Composer. @lorantalas and anyone else interested in this effort are encouraged to keep participating in Discord to make it happen 😄

**Comment by lorantalas** [comment]
Agreed. I will summarize our Discord discussion and put in into the issue, so intresting parties could get involved into discussion.

**Pull request closed without merging**
