### PR TITLE
BUGFIX Stop generating setup file

### PR DESCRIPTION
**Pull request by iadi7ya**
# Pull Request Check List

Resolves: #3163 

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### CODE REVIEW

**Review by iadi7ya — COMMENTED** [review]
Hi @abn All checks have passed. Thanks.

**Comment by zyv** [comment]
What you did was to edit Poetry's own `pyproject.toml`, which doesn't have any effect on Poetry-generated files, and is probably even harmful #hacktober

**Comment by iadi7ya** [comment]
Hi @zyv These chnanges fixes the #3179 , https://github.com/python-poetry/poetry/issues/3163#issuecomment-706446458

**Comment by zyv** [comment]
@iadi7ya please re-read my comment above, and give it some thought.

**Comment by iadi7ya** [comment]
> @iadi7ya please re-read my comment above, and give it some thought.

I have read you comment, but in that case what could be possible solution for that?

**Comment by zyv** [comment]
@iadi7ya https://github.com/python-poetry/poetry/issues/3163#issuecomment-706447242

**Review by abn — CHANGES_REQUESTED** [review]
@iadi7ya as @zyv correctly points out; your fix does not address the problem described in #3163. Please refer to the comment regarding where the problem lies. Feel free to reach out to us on Discord if you have further questioons.

**Comment by abn** [comment]
The required change is not in this project but `poetry-core`. Closing.

**Pull request closed without merging**
