### PR TITLE
Small poetry init fixes

### PR DESCRIPTION
**Pull request by wieczorek1990**
* Fixed invalid authors field population
* Fixed no info about skipping while adding packages

### CODE REVIEW

**Comment by dimbleby** [comment]
Why removing apostrophes - do they cause a problem?

They're quite common in some names - eg Ronnie O'Sullivan.  Why should they not be allowed in poetry projects?

**Comment by wieczorek1990** [comment]
Removing only from the beginning and ending.
Now instead of:
Łukasz Wieczorek ***@***.***>
I get:
’Łukasz Wieczorek’ ***@***.***’>
It is a bug and does cause error when publishing.

W dniu niedz., 3.07.2022 o 15:15 David Hotham ***@***.***>
napisał(a):

**Comment by wieczorek1990** [comment]
I had bad data inputed in `.gitconfig` with single quotation marks.
The problem is not existent.
Now the patch only fixes messages in `poetry init` to add info about skipping.

**Review by mkniewallner — APPROVED** [review]
Thanks!

**Pull request merged**
