### PR TITLE
Use per-package --index-url in export command (3269)

### PR DESCRIPTION
**Pull request by estyxx**
# Pull Request Check List

Resolves: #3269 

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

Add `--with-indexes` option to the export command in order to add `--index-url` per each package.

FYI this PR is related to Hacktoberfest :)

### CODE REVIEW

**Comment by abn** [comment]
@estyxx we will have to discuss the solution for this. The issue itself will not be resolved with this, I suspect there might be value in being able to toggle the indices (but might require another issue). Note on this however, we will have to make it opt-out instead of of-in. Otherwise this will become a breaking change that might cause issues for existing workflows. :(

**Comment by estyxx** [comment]
@abn I read your comments and I'm confused about the opt-out: as now the default requitement.txt is *without* per package indexing, so thought we want to make optional to include them... 
With opt-out, we are changing what is now the "default" and we will always include per-package-flag by default... 
But thinking now our goal is to ensure requirements.txt are exported in order to not choose the wrong (homonym) package during the installation, so including a per-package-flag by default can be the solution to this problem...

**Comment by abn** [comment]
> I read your comments and I'm confused about the opt-out: as now the default requitement.txt is _without_ per package indexing, so thought we want to make optional to include them...
> With opt-out, we are changing what is now the "default" and we will always include per-package-flag by default...

My thought here was that we could allow for "export requirements without any index" (opt-out of using indexes) as a new option. However, thinking about this now, there really is no "demand" for such a feature.

> But thinking now our goal is to ensure requirements.txt are exported in order to not choose the wrong (homonym) package during the installation, so including a per-package-flag by default can be the solution to this problem...

There are a few concerns here. 

The first being that it is not possible to have a per-package index. Because pip does not like that. If `pip` cannot consume it, the `requirements.txt` is pretty much useless. 

The second, which is a non-technical concern, is that we will be encouraging bad bahviour here by allowing "homonym" pacakges.

**Comment by neersighted** [comment]
Closing this as the exporter has been moved to https://github.com/python-poetry/poetry-plugin-export -- feel free to open an issue or PR there to discuss if this feature is desirable or not.

**Pull request closed without merging**
