### PR TITLE
Fix problem with deleting temporary folders on Windows (re-created patch #1032)

### PR DESCRIPTION
**Pull request by eblis**
When deleting temporary directories on Windows try a few times so we get around a Windows error, see issue #1031 for more details.

# Pull Request Check List

Resolves: #1031, #1032
Pull request #1032 is stale, but I took out the code from that and made the requested changes from comments (decreased timeout to 1s and added a test)

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by Secrus** [comment]
Hi, @eblis are you still interested in bringing that to Poetry?

**Comment by da1910** [comment]
If @eblis is not available then I am certainly interested, I've hit this issue several times now with our CI machines. What would need to be done? Is it just fixing the pre-commit checks?

**Comment by eblis** [comment]
Hey, sorry, I completely missed the updates in this issue.
What do you need done ?

**Comment by da1910** [comment]
pre-commit.ci autofix

**Comment by eblis** [comment]
From what I can tell the relevant code has been moved to another repository called `poetry-core`.

**Comment by da1910** [comment]
@Secrus We're approaching 2 months with the open PR from @eblis is there anything we can do to move the issue forward?

**Pull request closed without merging**
