### PR TITLE
All required features implemented

### PR DESCRIPTION
**Pull request by MAX-EINSTEIN**
# Pull Request Check List

Resolves: #3068 

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Review by abn — CHANGES_REQUESTED** [review]
Some re-work required of this one. 

Also, maybe consider looking at https://chris.beams.io/posts/git-commit/ on how to write a commit message. The PR summary and description could also use some work. 

PS: Providing verbose feedback since this came from a "Good First Issue".

**Comment by abn** [comment]
@MAX-EINSTEIN does this need to be marked for hacktoberfest? Also are you still working on this one?

**Comment by IgNoRaNt23** [comment]
Was just looking for this change. So, if @MAX-EINSTEIN isn't responding anymore, should I take over?

**Comment by neersighted** [comment]
@IgNoRaNt23 Please feel free to take over this PR! In light of the age of the review/staleness I'm closing this one for now.

**Pull request closed without merging**
