### PR TITLE
add support for `poetry env remove` when `virtualenvs.in-project = true`

### PR DESCRIPTION
**Pull request by ITProKyle**
# Pull Request Check List

Resolves: #2124

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

## What Changed

- `poetry env remove` argument now defaults to `.venv` for ease of use with the static value
- when `.venv` is passed as the `<python>` argument and `virtualenvs.in-project=true`, it will remove the `.env` directory in the root of the project

### CODE REVIEW

**Comment by abn** [comment]
@ITProKyle Apoligies for dropping the ball on this one. Feel free to ping on discord if something falls through the crack again. We appricate your contribution.

Can you rebase this change with latest master please? Also can we make `<python>` optional for `poetry env remove`? Defaulting to activated environment. This will also allow easier removal in the `in-project` case ase well.

**Comment by jidicula** [comment]
@ITProKyle is this PR still alive? I've encountered the bug that this fixes, so it would be great if this fix could get merged 🙂

**Comment by ITProKyle** [comment]
@jidicula - I could probably find some time to update the PR if it were to get reviewed. But, I don't want to waste the time if it's just going to sit for months to the point where I need to spend hours bring it back up to date for the third time.

Not having this functionality is still an annoyance for me as well.

**Comment by finswimmer** [comment]
Hello @ITProKyle,

yes please rebase this PR please. Don't hesitate to ping me on [Discord](https://discordapp.com/invite/awxPgve) for a review.

Thanks a lot for your contribution :+1: 

fin swimmer

**Comment by janwaltl** [comment]
Until this is fixed, simply removing the `.venv` folder does not seem to break anything with poetry.

**Comment by ITProKyle** [comment]
I really haven't had any time to revisit this to update it so anyone else is free to continue from where I left off.

Not that this isn't annoying and an inconvenience to not have but I have adapted to live without it. I use the following snippet in its absence either per project or the root directory for all my projects to cleanup all virtual environments in one go.

```console
find  -name ".venv" -type d -prune -exec rm -rf '{}' +
```

**Comment by neersighted** [comment]
Closing for now as this is long out of date/conflicted and `poetry env remove --all` does this -- special-casing can be added later if desired and will be easier from a clean slate.

**Pull request closed without merging**
