### PR TITLE
refactor: rework deprecation of get-poetry.py to include CI brownout and restructured messaging

### PR DESCRIPTION
**Pull request by neersighted**
This supersedes #6287 and #6281.

This takes a new approach to deprecation of `get-poetry.py`.

In CI (detected using `$CI`), we proceed with warnings, and a random brownout percentage:
```
$ CI=1 python3 get-poetry.py

Retrieving Poetry metadata

This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
You should migrate to https://install.python-poetry.org instead. Instructions are available at https://python-poetry.org/docs/#installation.

A CI environment has been detected! Due to the above deprecation, this installer is subject to an escalating brownout percentage (currently 5%)!
If you understand the above warning and wish to opt out of this brownout, set GET_POETRY_IGNORE_DEPRECATION=1 in the environment.

Version 1.2.0 is available but is not supported by this installer!
Version 1.1.15 will be installed as it is the latest version supported by this installer.
This is not the latest version of Poetry! If you wish to install the latest version, please migrate to the new installer as described above!

[install of 1.1.15]
```

The brownout is based on a percentile chance and looks like this when it triggers:
```
$ CI=1 python3 get-poetry.py

Retrieving Poetry metadata

This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
You should migrate to https://install.python-poetry.org instead. Instructions are available at https://python-poetry.org/docs/#installation.

A CI environment has been detected! Due to the above deprecation, this installer is subject to an escalating brownout percentage (currently 5%)!
If you understand the above warning and wish to opt out of this brownout, set GET_POETRY_IGNORE_DEPRECATION=1 in the environment.

This invocation of the installer has been terminated due to the brownout described above. Please carefully read the above notices and update your CI pipeline accordingly!

[failure]
```

The user can set `$GET_POETRY_IGNORE_DEPRECATION` to opt out of this:
```
$ CI=1 GET_POETRY_IGNORE_DEPRECATION=1 python3 get-poetry.py

Retrieving Poetry metadata

This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
You should migrate to https://install.python-poetry.org instead. Instructions are available at https://python-poetry.org/docs/#installation.

Version 1.2.0 is available but is not supported by this installer!
Version 1.1.15 will be installed as it is the latest version supported by this installer.
This is not the latest version of Poetry! If you wish to install the latest version, please migrate to the new installer as described above!

[install of 1.1.15]
```

For non-CI situations, by default we fail hard and early:
```
$ python3 get-poetry.py

Retrieving Poetry metadata

This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
You should migrate to https://install.python-poetry.org instead. Instructions are available at https://python-poetry.org/docs/#installation.

This installer will now exit. If you understand the above warning and wish to proceed anyway, set GET_POETRY_IGNORE_DEPRECATION=1 in the environment and run this installer again.

[failure]
```

The same `$GET_POETRY_IGNORE_DEPRECATION` variable can be set to allow the installer to work:
```
$ GET_POETRY_IGNORE_DEPRECATION=1 python3 get-poetry.py

Retrieving Poetry metadata

This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
You should migrate to https://install.python-poetry.org instead. Instructions are available at https://python-poetry.org/docs/#installation.

Version 1.2.0 is available but is not supported by this installer!
Version 1.1.15 will be installed as it is the latest version supported by this installer.
This is not the latest version of Poetry! If you wish to install the latest version, please migrate to the new installer as described above!

[install of 1.1.15]
```

As before, specifying an unsupported version is an error:
```
$ GET_POETRY_IGNORE_DEPRECATION=1 python3 get-poetry.py --version 1.2.0

Retrieving Poetry metadata

This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
You should migrate to https://install.python-poetry.org instead. Instructions are available at https://python-poetry.org/docs/#installation.

Version 1.2.0 is not supported by this installer! Please specify a version prior to 1.2.0a1 to continue!

[failure]
```

Specifying a supported version explicitly will suppress the warnings generated during the version selection process:
```
$ GET_POETRY_IGNORE_DEPRECATION=1 python3 get-poetry.py --version 1.1.15

Retrieving Poetry metadata

This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
You should migrate to https://install.python-poetry.org instead. Instructions are available at https://python-poetry.org/docs/#installation.

[install of 1.1.15]
```

### CODE REVIEW

**Review by finswimmer — APPROVED** [review]

**Comment by chlasch** [comment]
What is the rationale behind introducing a probability of a brownout? Won't this lead to people just retrying their CI pipelines, instead of addressing the deprecation?

**Comment by neersighted** [comment]
> What is the rationale behind introducing a probability of a brownout? Won't this lead to people just retrying their CI pipelines, instead of addressing the deprecation?

We previously failed hard, however there was much wailing and gnashing of teeth from production environments in which they had not pinned a version, and were unable to migrate to 1.2. As a temporary band-aid (though this deprecation was started over a year ago), the plan is to introduce a brownout we will aggressively increase the chance of (the exact timeline is still being decided), before the wholesale removal of the script.

**Comment by remram44** [comment]
WTF this is not how a "deprecation" works! You literally released 1.2 today, don't start breaking people's builds right away.

Please don't break Poetry everywhere around the world every time you release an update! No one wants to use a tool that's so unreliable, on purpose. The 1.1 release already caused crashes for 1.0.* versions when the lock file was updated, now you do this.

A message is enough to signify deprecation. Please leave time for people to update organically before you force their hands with a browout. The base probability of 5% is really high and if I understand correctly it's even higher in CI?

**Comment by remram44** [comment]
You can't go straight in a single day from "the new installer is not ready" to "the old installer will blow up your builds on purpose". And calling this "deprecation" is a bad joke.

**Comment by remram44** [comment]
This even happens if installing a *locked* version of Poetry, e.g. `get-poetry.py --version 1.1.12`. You are building Poetry, surely you understand the importance of people locking down the versions of the packages they depend on? Why do you think Poetry itself gets to go against everything you are trying to facilitate, and blow up if someone chooses to depend on a locked version?

How would you feel, as the authors of Poetry, if half the packages that Poetry installed from a lock file got remotely disabled by their authors when they are no longer the latest version?

Can you please at least disable this terrible mis-feature when someone uses the `--version` flag?

**Comment by jonapich** [comment]
@remram44 there's a discussion about this change here in #6314

**Comment by connor-create** [comment]
Yeah I'm definitely migrating away from this dependency manager and seriously talking to all the groups I use this within about getting off of it.  This is possibility one of the dumbest things I've ever seen in software.

**Comment by neersighted** [comment]
Hello @connor-create -- I'm sorry to hear you're frustrated, but I hope you can work through that frustration and engage in discourse with the project and community (since I assume that's what brought you here).

This PR does not represent the current state of the `get-poetry.py` script -- it was a compromise aimed at one specific group/scenario, but after dialogue with other end users we ended up with a new strategy that likely pleases no one, but doesn't break things for anyone either. Please see #6377 for the current state of affairs.

Given you speak with confidence and authority about best practices in software development, I hope this hasn't disrupted things for you too much -- we very explicitly made a carve-out in the new behavior for those who are pinning a version.

If there is some trade-off or gotcha we have missed, please contribute to the issue there.

**Comment by remram44** [comment]
Thanks for your virtue signaling, it really helps the ecosystem to have people not affected by the issue come and comment once it has been fixed, based on having watched a YouTube video. On closed tickets, no less.

**Comment by neersighted** [comment]
The appropriate place to discuss changes related to get-poetry.py is #6377. Please direct your comments there, and not directly to my email inbox or to closed PRs/issues.

**Pull request merged**
