### PR TITLE
when "disabled", keyring uses a "null" keyring and should be unavaila…

### PR DESCRIPTION
**Pull request by lakinwecker**
…ble.

# Pull Request Check List

Resolves: #5250

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

I didn't see any tests or docs for this part of the code, happy to update them as required.

### CODE REVIEW

**Comment by abn** [comment]
@lakinwecker can you add some regression test coverage for this?

**Comment by lakinwecker** [comment]
@abn I looked for tests related to this stuff and failed to find any.  Are there any other unit tests that do things similarily that I can follow to make tests? If so, I can try and add them, yes.

**Comment by radoering** [comment]
@lakinwecker Tests are in [test_password_manager.py](https://github.com/python-poetry/poetry/blob/master/tests/utils/test_password_manager.py). Probably, you should add two tests similar to https://github.com/python-poetry/poetry/blob/15f6ec1758d783d4cb3070a8027725bc611c0a90/tests/utils/test_password_manager.py#L190-L195

one with a simple null and one with a chained null. (And maybe you should rename the fixture `with_chained_keyring` to `with_chained_fail_keyring` so you can add `with_chained_null_keyring`). The fixtures are here: https://github.com/python-poetry/poetry/blob/15f6ec1758d783d4cb3070a8027725bc611c0a90/tests/conftest.py#L109-L127

**Comment by lakinwecker** [comment]
`test_keyring_with_chainer_backend_and_not_compatible_only_should_be_unavailable` doesn't fail when you mess with the "fail" code that I modified.  So I'm not convinced this test properly exercises it.

**Comment by lakinwecker** [comment]
Alright, the mocks were wrong for those chainer tests. I fixed them and now the tests fail if I change the name of the 'bad' keyrings in the `password_manager.py` checks.  So, I think this adds to tests to properly exercise it.

Is there documentation I should also update?

**Pull request merged**
