### PR TITLE
adds fallback behavior for non-ms shells

### PR DESCRIPTION
**Pull request by bmarroquin**
# Pull Request Check List

Resolves: #6495

- [ ] Added **tests** for changed code.

Confirmed working on MS Powershell, Powershell 7, cmd and git bash

### CODE REVIEW

**Review by neersighted — CHANGES_REQUESTED** [review]
A couple thoughts -- `args` should be hoisted instead of being part of an `else` branch.

However, I'm wondering about this whole approach. Doesn't `pexpect` work on Windows? Why not use the same code path we use on Unix OSes as much as possible, and keep the special-casing to Windows Powershell and cmd.exe?

**Comment by bmarroquin** [comment]
I'll give it a shot

**Comment by bmarroquin** [comment]
`pexpect's` windows support is missing the `interact` method. Without that, you can't run a sub shell or reuse any of the unix code path. I tried a few things but none of them worked.

**Review by neersighted — APPROVED** [review]
LGTM -- this class is heavily overloaded and needs to be refactored, but this was a regression in 1.2 and we shouldn't let the refactor block the fix.

**Pull request merged**
