### PR TITLE
respect hash algorithm when verifying downloaded archives.

### PR DESCRIPTION
**Pull request by kaos**
Signed-off-by: Andreas Stenius <andreas.stenius@svenskaspel.se>

Resolves: #4085

- [x] Added **tests** for changed code.

Depends on python-poetry/poetry-core#196, so marked as draft until there is a new poetry-core version we can use here.

### CODE REVIEW

**Review by neersighted — CHANGES_REQUESTED** [review]
Hey @kaos -- this looks good in light of the past state of the `master` branch, but things have changed... A fusion of your (and the other PR) to `poetry-core` has landed, and another PR has factored out the hash checking code. Could you rebase your changes/new tests on top of those? I'd like to get this landed to fix Artifactory support.

**Comment by neersighted** [comment]
Should close #4578 as well.

**Comment by kaos** [comment]
It would be more effective if someone who knows the code does this. I'm not up to speed with what changes have been made, nor what changes I made any more.
It is a small diff, so shouldn't be that hard to re-implement either.

**Comment by neersighted** [comment]
Successor PR (#4740) created!

**Pull request closed without merging**
