### PR TITLE
python 3.12 in pipelines

### PR DESCRIPTION
**Pull request by dimbleby**
expecting this to fail per #7766, let's check that's true and see whether anything else shows up

### CODE REVIEW

**Comment by dimbleby** [comment]
not sure what's with the ubuntu and macos pipeline failure now, but the good news is that the `__getattr__` that seems to be recursed on does not exist in the main branch of poetry-core - so with any luck releasing that will solve this.

(There's a corresponding `__getattr__` now in poetry: I want to remove that too - but doing so only becomes possible when poetry-core is released.  So probably clean 3.12 pipelines is just blocked on a poetry-core release)

I've no idea what the windows failure is about

**Comment by dimbleby** [comment]
getting closer

- virtualenv behaves differently at python 3.12, per their changelog:

> Do not install wheel and setuptools seed packages for Python 3.12+. To restore the old behaviour use:
>
>    for wheel use VIRTUALENV_WHEEL=bundle environment variable or --wheel=bundle CLI flag,
>    for setuptools use VIRTUALENV_SETUPTOOLS=bundle environment variable or --setuptools=bundle CLI flag.
>
> By [@chrysle](https://github.com/chrysle). ([#2487](https://github.com/pypa/virtualenv/issues/2487))

so I suppose code needs writing to deal with that.  (I'm not in any hurry to get there, if anyone would like to contribute then please don't wait on me)

and there's still something screwy on windows which I haven't looked at but I imagine is likely someone else's bug that will be sorted in due course.  Probably.

**Comment by dimbleby** [comment]
looks like whatever the screwy thing was on windows has now gone away, so all that is left is the virtualenv behaviour change

**Comment by dimbleby** [comment]
re the virtualenv behaviour change I've taken the view that poetry should roll with it and head in the same direction of not installing setuptools and wheel in new environments, certainly on new python.

then there's a bit of a rework to make sure that they _are_ installed in the one case where poetry itself wants them

a behaviour change here is that poetry no longer automatically installs `wheel` by default alongside `pip`, this really shouldn't be necessary.  (By way of comparison, `python -m venv` does not install `wheel`).  I suppose we could continue to install `wheel` at python < 3.12, but that seems likely to cause more confusion than it solves.

**Comment by radoering** [comment]
> re the virtualenv behaviour change I've taken the view that poetry should roll with it and head in the same direction of not installing setuptools and wheel in new environments, certainly on new python.

I agree.

> I suppose we could continue to install `wheel` at python < 3.12, but that seems likely to cause more confusion than it solves.

Not sure about that. I have no idea if there are users who rely on it but I suppose from a user perspective it would be more like a clean cut to keep setuptools and wheel for < 3.12 and drop it only for >= 3.12. On the other side, the current design is quite weird because we don't have a `no-wheel` config option and introducing it now does not seem very alluring so maybe just risk the hassle.

**Comment by dimbleby** [comment]
I'm pretty sure that putting `setuptools` and `wheel` into the project environment shouldn't be useful for anyone in the modern world of isolated builds.  (Except those who have forgotten to declare the dependency and have been getting away with it because of this behaviour: but those people should fix their dependencies.)

In the long run it's probably desirable to lose any options or code that make a special case of those packages, but I've tried to rein in any such ambitions in this merge request...

3.12.0 is due at the start of October.  While there's obviously no obligation to be instantly ready for that, it is approaching time to make any decisions that need making.

**Comment by Secrus** [comment]
My take on that would be that we should only leave `pip` in the project environment, starting from now. Since this is now a default for Python 3.12+, I don't see why we should stick to a different set of rules. I would add a note about that in the next release blog post and changelog and add deprecation/future warning to the environment creation code, that we will be removing setuptools and wheel installation in project venv for older pythons in let's say, 2 releases.

**Comment by radoering** [comment]
> I would add a note about that in the next release blog post and changelog

Agreed. We should mention the difference between Python 3.12 and older versions, as well as the removal of `wheel` for older versions (if we merge the PR as is).

> and add deprecation/future warning to the environment creation code, that we will be removing setuptools and wheel installation in project venv for older pythons in let's say, 2 releases.

I don't think it's necessary to change the behavior for `setuptools`. Of course, we could, but I wouldn't spend the effort but just let the old behavior fade out together with the older Python versions.

`wheel` is already removed (as per this PR) and it would require additional effort to keep the old behavior for older Python versions. I don't think the changed behavior is a big thing, so I'd probably go with dimbleby and risk this change.

**Review by radoering — APPROVED** [review]

**Pull request merged**
