### PR TITLE
Documentation: Add no interaction flag to website

### PR DESCRIPTION
**Pull request by GabrielSimonetto**
# Pull Request Check List

Resolves: #2466

A small PR to update documentation on the website

Edit:
From [here](https://github.com/python-poetry/poetry/issues/3152)
`Please indicate explicitly that your contribution is related to hacktoberfest, especially if it is an extremely small change (formatting fixes, typo fixes etc.). Openness and tranperency is encouraged. `

I would like to add I am currently involved in a [hacktoberfest event](https://organize.mlh.io/participants/events/4721-caravela-hacker-club-online-sprints-in-florianopolis).

### CODE REVIEW

**Comment by GabrielSimonetto** [comment]
@python-poetry/Documentation

**Comment by GabrielSimonetto** [comment]
@python-poetry/documentation

**Comment by GabrielSimonetto** [comment]
I wonder if there was a way I could generate the website myself in order to see if my changes worked? There's always the chance I didn't understood something in the process to build the documentation, and that could be helpful in future contributions...

**Comment by abn** [comment]
You could do `tox -e doc` to generate the documentation, however since the site styling source is not public you will not be able build it entirely. 

We really do appreciate your thoroughness. :)

**Review by stephsamson — APPROVED** [review]

**Pull request merged**
