### PR TITLE
Equivalent behaviour to pip install --find-links

### PR DESCRIPTION
**Pull request by cc-a**
# Pull Request Check List

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

# The What

This PR partially satisfies #1391. This PR implements a new repository class that reproduces the behaviour of the [--find-links](https://pip.pypa.io/en/stable/reference/pip_wheel/#find-links) flag to `pip install`. This allows installation of packages from online locations not compliant with Pep 503. 

# The How

The new class FindLinksRepository is implemented as a subclass of LegacyRepository as the desired behaviours are very similar with only slight changes in expected directory structure. Minor changes were made to LegacyRepository to provide functions that could be overwritten in the subclass. Combined with implementing FilteredPage as a subclass of Page this provides a fairly minimal approach to implementing this new functionality. A few minor associated changes in factory.py and pip_installer.py were required to accommodate the new repository class. 

# The Testing

The majority of the business logic of FindLinksRepository is derived from LegacyRepository and hence testing of this has not been repeated. Instead testing focuses on making sure that the behaviour of the major public functions of LegacyRepository is recreated with an appropriately structured test set.

A simple high level test can be performed using pytorch as an example. Create the below entry in a pyproject.toml:

```toml
[tool.poetry.dependencies]
python = "^3.7"
torch = "1.2.0+cpu"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/torch_stable.html"
find_links = true
```
Then `poetry install`.

# Not done yet

The behaviour of --find-links to install from local paths or file:// urls has not yet been replicated. I will follow up with another PR for this functionality if this one is successful.

### CODE REVIEW

**Comment by jkyl** [comment]
Thank you so much for this PR! The PyTorch example mentioned in your write-up is exactly my use case. Right now the issue that this PR addresses is completely blocking me from accomplishing a platform-independent build with PyTorch using Poetry. I hope this is merged ASAP!

**Comment by cc-a** [comment]
Glad to hear it @jkyl I've rebased to clear the merge conflict which had the side benefit of removing the spurious test failures on Windows which should hopefully smooth the process.

**Comment by jkyl** [comment]
@sdispater any chance of a review?

**Comment by aviramha** [comment]
Any news on this matter?

**Comment by abn** [comment]
@cc-a can you rebase this with current master resolve conflicts please? Happy to review this.

**Comment by cc-a** [comment]
So as far as I'm concerned this is good to go. I'm unable to reproduce the linting error locally (different isort versions?) so am not sure whats best to do about that.

**Comment by Korijn** [comment]
Please be aware that even if this PR is merged, issue https://github.com/python-poetry/poetry/issues/2543 still blocks a number of pytorch packaging scenarios as well.

**Comment by masonkirchner** [comment]
@abn @cc-a Can we revisit this PR? This functionality would be required for my team to adopt poetry. Happy to help with the merge conflicts, or jump in elsewhere as needed.

**Comment by simonrouse9461** [comment]
Any update on this PR?

**Comment by PgLoLo** [comment]
Any updates?

**Comment by Secrus** [comment]
Hi, @cc-a are you still interested in bringing this to Poetry? There had been some changes to the codebase, so your PR would probably be a complete do-over.

**Comment by mboisson** [comment]
> This is actually superseded by the new 'simple' repo type that allows installing from a HTML page of links. Thanks for the PR, and please test the new code in master to make sure it works for your use case!

is there any tool to generate such HTML page of links ?

**Pull request closed without merging**
