### PR TITLE
Enable parallelization in CI

### PR DESCRIPTION
**Pull request by aviramha**
As discussed in https://github.com/python-poetry/poetry/pull/2648 this check is probably no longer needed.

### CODE REVIEW

**Comment by aviramha** [comment]
I'm not sure why the tests failed - is develop broken or something?

**Comment by abn** [comment]
```
>       assert expected == tester.io.fetch_output()
E       AssertionError: assert '\nUpdating de...1.2 9cf87a2)\n' == '\nUpdating dep... tag found.\n\n'
E           
```
Might want to strip the values before comparision.

**Comment by aviramha** [comment]
Thanks! I'll commit it soon. I wonder how I broke that test with my change tho. The parallel feature prints more new lines?

**Comment by aviramha** [comment]
I think it's OK now - Cirrus CI seems to fail randomly (before even starting to test). I don't think it's related..

**Comment by abn** [comment]
> Thanks! I'll commit it soon. I wonder how I broke that test with my change tho. The parallel feature prints more new lines?

Output testing across python versions and platforms can get wierd. The wierd bit is that the new line occured only for one env.

I have retriggered the failing Cirrus CI job.

**Comment by aviramha** [comment]
@abn the cirrus bug seems to be known and was declared as fixed,  I sent the failing task in the relevant issue. Hopefully they'll reopen it.
https://github.com/cirruslabs/cirrus-ci-docs/issues/592

**Comment by aviramha** [comment]
Looks good now, any comments?

**Pull request merged**
