### PR TITLE
doc(configuration): improve documentation

### PR DESCRIPTION
**Pull request by mkniewallner**
# Pull Request Check List

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

Bunch of improvements over `Configuration` documentation:
- Better show default value of options
- Add some missing `Introduced in <VERSION>` notes
- Add backticks around types for better readability

Will backport to `1.2` branch before final release.

### CODE REVIEW

**Review by Secrus — DISMISSED** [review]

**Comment by mkniewallner** [comment]
Sorry, for the last minute [new commit](https://github.com/python-poetry/poetry/pull/6254/commits/59717b0b35ae04e0cf1f18d18cdef7312e6f4109), thought it would look better for people with OCD like me :smile:

**Comment by Secrus** [comment]
@mkniewallner what was that last commit about? My understanding is that you wanted to sort options alphabetically, but those seem really out of order now...

**Comment by mkniewallner** [comment]
> @mkniewallner what was that last commit about? My understanding is that you wanted to sort options alphabetically, but those seem really out of order now...

https://github.com/python-poetry/poetry/pull/6254/commits/59717b0b35ae04e0cf1f18d18cdef7312e6f4109 and the [deployed website](https://website-ecp7av1f7-python-poetry.vercel.app/docs/configuration/#available-settings) (you can compare with the [current documentation](https://python-poetry.org/docs/master/configuration/#available-settings)).

**Comment by Secrus** [comment]
> [59717b0](https://github.com/python-poetry/poetry/commit/59717b0b35ae04e0cf1f18d18cdef7312e6f4109) and the [deployed website](https://website-ecp7av1f7-python-poetry.vercel.app/docs/configuration/#available-settings) (you can compare with the [current documentation](https://python-poetry.org/docs/master/configuration/#available-settings)).

Would you mind doing top level sorting too? My OCD fires up seeing `http*` after `virtualenv*` etc...

**Comment by mkniewallner** [comment]
> > [59717b0](https://github.com/python-poetry/poetry/commit/59717b0b35ae04e0cf1f18d18cdef7312e6f4109) and the [deployed website](https://website-ecp7av1f7-python-poetry.vercel.app/docs/configuration/#available-settings) (you can compare with the [current documentation](https://python-poetry.org/docs/master/configuration/#available-settings)).
> 
> Would you mind doing top level sorting too? My OCD fires up seeing `http*` after `virtualenv*` etc...

I didn't want to update those ones because they are all related to `repositories`, so kinda make sense to keep them all together.

**Review by Secrus — APPROVED** [review]

**Pull request merged**
