### PR TITLE
Add details to basic usage docs about setting `VIRTUAL_ENV_DISABLE_PROMPT`

### PR DESCRIPTION
**Pull request by savannahostrowski**
# Pull Request Check List

Resolves: #1853

I don't think that these tasks apply for documentation changes. Happy to make updates for tone, more details, links to virtualenv docs, etc. 
- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by radoering** [comment]
IMO, we should move this either into https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment or https://python-poetry.org/docs/cli/#shell. Currently, it's in a section that does not even mention `poetry shell` and IIUC this hint is only relevant for `poetry shell`.

**Comment by savannahostrowski** [comment]
Ah, yeah. You're right - I've gone ahead and moved it lower down in the activating the virtual env section of the basic usage doc. It seemed to fit a little more naturally there.

**Review by radoering — CHANGES_REQUESTED** [review]
Now, the paragraph is in between "manually activating the virtualenv" and "deactivating a manually activated virtualenv". IMO, it should be moved up one paragraph (before manually activating the virtualenv).

**Comment by savannahostrowski** [comment]
Sure thing! Done

**Review by radoering — APPROVED** [review]

**Pull request merged**
