### PR TITLE
Remove reference to old scripts extras feature

### PR DESCRIPTION
**Pull request by Secrus**
Resolves: #8902

### CODE REVIEW

**Comment by radoering** [comment]
We probably should print a deprecation warning somewhere as proposed in the issue.

**Comment by Secrus** [comment]
> We probably should print a deprecation warning somewhere as proposed in the issue.

Yeah, that would be a separate PR in core, as that's where the code is.

**Comment by radoering** [comment]
Do you want to create that PR? I feel like we should undocument and deprecate it at the same time. It don't like the idea to make this an undocumented but not yet deprecated feature.

**Comment by radoering** [comment]
I just created python-poetry/poetry-core#690 so we might include it in the next release.

**Review by radoering — APPROVED** [review]

**Pull request merged**
