### PR TITLE
Update packaging requirement to support 21.0

### PR DESCRIPTION
**Pull request by NeilGirdhar**
Fixes https://github.com/python-poetry/poetry/issues/4264

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
@sdispater Would you mind taking a quick look at this single line change?

**Comment by NeilGirdhar** [comment]
Could even consider ">=" since it looks like packaging isn't going with semantic versioning.

**Comment by kkirsche** [comment]
> Could even consider ">=" since it looks like packaging isn't going with semantic versioning.

https://packaging.pypa.io/en/latest/development/release-process.html seems to confirm this, though  I haven't reviewed their Noxfile

**Comment by hugovk** [comment]
> > Could even consider ">=" since it looks like packaging isn't going with semantic versioning.
> 
> [packaging.pypa.io/en/latest/development/release-process.html](https://packaging.pypa.io/en/latest/development/release-process.html) seems to confirm this, though I haven't reviewed their Noxfile

Correct, `packaging` (like pip) follows Calendar Versioning (https://calver.org/): `YY.N` is the year number and a sequential number.

`packaging` 21.2 has recently come out: https://pypi.org/project/packaging/#history

**Review by hugovk — DISMISSED** [review]

**Review by neersighted — APPROVED** [review]
Rebased onto current master -- I don't see any reason why we can't unclamp this. LGTM!

**Pull request merged**
