### PR TITLE
Fix handling of init dependencies

### LINKED ISSUE #711: "poetry init --dependency django" does nothing
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu Xenial
- **Poetry version**: o.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/nottrobin/dddb94232b2d79f089ea7ef3b3dab4a4

## Issue

If I do:

``` bash
poetry init --dependency django
```

It walks me through the same guide as normal, and if when it asks if I went to define dependencies I select "no", then it doesn't add Django to `pyproject.toml` as a dependency, so `--dependency django` effectively did nothing.

It should either:

- Edit the guide to ask if you want to specify any *further* dependencies, and maybe indicate that it's going to install Django anyway; or
- Error saying "`--dependency` is only compatible with `--no-interaction`"

### PR DESCRIPTION
**Pull request by silenc3r**
- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

Make sure that command line dependencies (and dev dependencies) are always handled properly.

Closes #711.

### CODE REVIEW

**Comment by silenc3r** [comment]
Python 2.7 and 3.5 are failing because of different ordering of dependencies in pyproject.toml file.
Python 2.7 seems to sort dependencies in reverse order, while in Python 3.5 order is not deterministic.

I guess I'll have to use multiple asserts per test as workaround.

**Comment by silenc3r** [comment]
Failures look unrelated.

**Comment by silenc3r** [comment]
Tests succeed when run in isolation, i.e. ``pytest tests/console/commands/test_init.py`` but fail when run with ``make test``.

``test_interactive_with_dependencies`` is broken on current master as well.

It seems to be some kind of bytes to string conversion error in Cleo.

Sorry but I don't have time to investigate that.

**Comment by brycedrennan** [comment]
Why do you say the tests are broken on master? I don't see any recent failures:

**Comment by silenc3r** [comment]
It fails locally both on OpenSUSE Tumbleweed (Python 3.7.3) and Fedora 30 (Python 3.7.4).

Steps to reproduce:

**Comment by brycedrennan** [comment]
Interesting - thanks for the heads up on that.

**Comment by finswimmer** [comment]
Hey @silenc3r,

could you please rebase your PR on the current master branch? Thanks a lot!

fin swimmer

**Comment by finswimmer** [comment]
@silenc3r I forked your PR and make the rebase: https://github.com/python-poetry/poetry/pull/2587

Thanks a lot for your contribution :+1:

**Pull request closed without merging**
