### PR TITLE
enable strictness flags for mypy

### PR DESCRIPTION
**Pull request by dimbleby**
Enable strict mypy checking, and fix errors arising.

### CODE REVIEW

**Comment by dimbleby** [comment]
closer now that #5485 is merged, I think we need
- #5279 so that the pipeline does its typechecking in the proper environment
- poetry-core to be published with py.typed, so that we recognise types from that project

**Comment by dimbleby** [comment]
this looks as though it has got worse ince #5279 was merged, but that's only because we now run mypy on all platforms.  We're now just waiting on publishing a `poetry-core` that includes `py.typed`.

Maybe it's worthwhile updating this MR to treat `poetry-core` as untyped, and then reverse those changes when the next version of that project is published.

**Comment by dimbleby** [comment]
> Maybe it's worthwhile updating this MR to treat poetry-core as untyped

I've done this, in the hope of getting the improved mypy settings merged sooner rather than later.

When the next poetry-core is published, we'll get a handful of warnings about unnecessary `# ignore: type[...]` markers, which can be resolved simply by removing them.

**Review by neersighted — APPROVED** [review]
This looks really good, and the un-cargo-culted mypy options are a breath of fresh air. I agree with the incremental approach -- better to get this work in and prevent the need to endlessly rebase than to wait for the perfect one-shot change.

**Comment by neersighted** [comment]
@dimbleby Needs another rebase, sorry!

**Comment by dimbleby** [comment]
More conflicts, and also a new mistake to fix... any chance we can get this merged?

**Review by neersighted — APPROVED** [review]
Let's ship it :)

**Comment by neersighted** [comment]
Oh bloody hell more conflicts... Sorry! It looks good to merge as soon as the next rebase is done.

**Comment by dimbleby** [comment]
@neersighted this is not currently conflicted, it should merge cleanly

**Comment by neersighted** [comment]
Ah, looks like my local pull wasn't up to date. Here we go!

**Pull request merged**
