### PR TITLE
support git subfolder (#755)

### PR DESCRIPTION
**Pull request by finswimmer**
This PR implements the possibility to add git dependencies, where the package is located within a subdirectory  of the repository.

This was orginaly implemented in https://github.com/python-poetry/poetry/pull/1822, but needs rework due to the new poetry_core package. 

**Merging this PR requires merging of https://github.com/python-poetry/core/pull/9 in poetry_core as well.**

The path to the subdirectory can be specified as follows:

```
poetry add "git+https://github.com/demo/project_in_subdirectory.git?subdirectory=pyproject-demo"
```

Where `pyproject-demo` is a subfolder relative to the root after checkout the repository. This can be combined with the revision tag:

```
poetry add "git+https://github.com/demo/project_in_subdirectory.git#dev?subdirectory=pyproject-demo"
```

To specify the subdir in the `pyproject.toml` a new argument `subdirectory` was introduced:

```
mypackage = {git = "https://github.com/demo/project_in_subdirectory.git", rev = "dev", subdirectory = "pyproject-demo"}
```

To implement this feature is was necessary  to checkout the repository first to a temporary folder and copy the desired folder to it's destination. For this a new `DownloadTmpDir` class was implemented, which avoids downloading from the same git source multiple times, during run time.

I would like to get some feed back from people, who can test this on a real world use case. Especially if this all works as expected.

Implements: #755 

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://python-poetry.org/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

### CODE REVIEW

**Comment by pwhissell** [comment]
what is the status on this? Is there an E.T.A. ?

**Comment by finswimmer** [comment]
Hello @pwhissell ,

we are still discussing how to test changes in `poetry` that rely on changes in `poetry-core` made at the same time. There are some ideas about it, but we don't have the time until now to establish such a pipeline. So unfortunately this PR is blocked until we solved the testing problem.

fin swimmer

**Comment by pwhissell** [comment]
Thank you for your quick resopnse @finswimmer 
Are you guys prioritizing that testing pipeline for its implementation in 2020 or is it further down the priority queue?

**Comment by pwhissell** [comment]
In version 20.2.2, pip now supports this out of the box
https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

**Comment by shaunc** [comment]
@finswimmer -- couldn't you push the changes to poetry core separately (with tests), and then push the rest afterwards? Don't let the bureaucracy get you down! :)

**Comment by finswimmer** [comment]
@shaunc Yes and no :) If I want to go that way, the pushed code to core must also be released. Once this is released I could push the code the poetry.

We have to finde a better solution and I'm sure we will in the near future. We will run in this problem more often whenever a new feature is implemented in poetry.

**Comment by shaunc** [comment]
One solution over in javascript land is to use a monorepo, so that releases are automatically coordinated. That use case is supported, in part, by this very PR! :)

**Comment by kpeterson-sf** [comment]
Looking forward to this one.  Solves a huge issue for me.

**Comment by danihodovic** [comment]
Useful feature for monorepos that contain a collection of packages such as https://github.com/man-group/pytest-plugins

**Comment by rubenlopezlozoya** [comment]
Guys, any updates on this?

**Comment by finswimmer** [comment]
I'm closing this PR and the related in https://github.com/python-poetry/poetry-core/pull/9 for the following reasons:

* poetry's code base has changed a lot. I guess it would be easier to start from scratch then trying to adopt the current implementation
* I'm not aware of any PEP that says how to describe a git dependency located in a subfolder

**Comment by tigerhawkvok** [comment]
@finswimmer If you specifically want to check for git subfolders, looking at submodules or subtrees is probably the right way to go

**Pull request closed without merging**
