### PR TITLE
self.run("clone", "--recurse-submodules", repository, str(dest))

### PR DESCRIPTION
**Pull request by matemax**
Fixes: #1828 
Closes: #611 

# Pull Request Check List

- [x] Added **tests** for changed code. 
I not found how implement test for these case 
- [x] Updated **documentation** for changed code.
I not found docs about clone git dependencies.

### CODE REVIEW

**Comment by matemax** [comment]
closes https://github.com/python-poetry/poetry/issues/1828

**Comment by matemax** [comment]
@finswimmer, i don`t know that this PR ready for review or not because i not found tests which checking a correct repo  cloning and docs about clone strategy.

**Comment by matemax** [comment]
@sdispater tell me pleaze what should i do yet in it PR?

**Comment by matemax** [comment]
Is there any news?

**Comment by matemax** [comment]
@sdispater, is there any question, suggestions?

**Comment by matemax** [comment]
@finswimmer , @sdispater, Sorry guys, this feature is very helpful for me. What should i do for  accepting this PR?

**Comment by finswimmer** [comment]
Hello @matemax,

@sdispater needs to find some time for reviewing and merging it :smiley: 

fin swimmer

**Pull request closed without merging**
