### PR TITLE
recurse clone submodules

### PR DESCRIPTION
**Pull request by matemax**
Fixes: #1828 
Closes: #611 

# Pull Request Check List

- [x] Added **tests** for changed code. 
I not found how implement test for these case 
- [x] Updated **documentation** for changed code.
I not found docs about clone git dependencies.

### CODE REVIEW

**Comment by matemax** [comment]
closes #1828

rebase and reopen(#1826 )

**Comment by matemax** [comment]
@finswimmer, i rebase and reopen(#1826 )

**Comment by matemax** [comment]
Any Feedback?

**Comment by fabiopedrosa** [comment]
@finswimmer @matemax for me this merge has broken the use of `https:// .... .git` schema. e.g. this now fails: 
```
[CalledProcessError]
Command '['git', 'clone', '--recurse-submodules', 'https://github.com/darklow/django-suit.git', 'C:\\Temp\\pypoetry-git-django-su0mrul0xy']' returned non-zero exit status 128.
```

**Comment by finswimmer** [comment]
Hello @fabiopedrosa ,

could you please open a new issue for this and describe how one can reproduce the problem?

fin swimmer

**Comment by matemax** [comment]
Hello @fabiopedrosa, the command 
```bash
git clone --recurse-submodules https://github.com/darklow/django-suit.git C:\\Temp\\pypoetry-git-django-su0mrul0xy
```
executes correct

**Pull request merged**
