### PR TITLE
Work around for --no-deps failure in pip

### LINKED ISSUE #1689: Installing directory poetry package with dependencies in secondary source fails
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **MacOS 10.14**: 
- **1.0.0b8**: 

## Issue
Due to https://github.com/pypa/pip/issues/7444 installing a directory which is managed by poetry or has a pyproject.toml file present will cause the `--no-deps` argument to be ignored. 

This can go unnoticed as long as you are only working with pypi dependencies but when your package depends on a private pypi repository this causes installs to fail.

### PR DESCRIPTION
**Pull request by wakemaster39**
I am not sure about the checklist, I went looking at the unit tests and there is no coverage for this area of the pip_installer so not sure where I should be targeting to start with that.

I don't think this needs to be documented as it should all be invisible in the background but maybe we want something visible  so users know it is messing around like this?

I also wasn't sure as this changes behaviour but it is also a bug fix. I can close and resubmit if it is preferred against the develop branch. I am impacted by this issue now so I treated it as a bug.

This should resolve #1689 

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by finswimmer** [comment]
Whoooah, thanks a lot! :rocket: :guitar: 

This one was making me headache the last days. I have already found out, that it has something to do with `pip` but not what goes wrong exactly.

I'm not sure if it is a good idea to rename the `pyproject.toml` to something cryptic. There might be cases where the reverting to `pyproject.toml` doesn't work. So I would prefer something like `pyproject.toml.orig` or similar.

fin swimmer

**Comment by wakemaster39** [comment]
happy to do an append or whatever makes the most sense here, I typically don't see guids in my code base so I would know what I am looking for. It is also that way to avoid the collision, but appending to the file name would also solve this.

**Comment by wakemaster39** [comment]
This is a hack, I don't think this should be merged in but I will leave it here if I can't find a better alternative. I will link the information I have found in the issue and try and see if I can come up with a proper fix.

**Comment by finswimmer** [comment]
Hello @wakemaster39 ,

yes this is a workaround and I would like to see a proper solution instead just like you. Thanks for your investigations and informations in the issue! I hope @sdispater has also some time to look at this.

What works for me in the meantime, is to make sure that within the venv the pip version is <19.

**Comment by gvskalyan** [comment]
When would this be merged into master?

**Comment by finswimmer** [comment]
Hey @gvskalyan,

it is unclear if this ever get merged, because this is "just" a hack and not a clean solution for the underlying problem. See also #1689.

@sdispater has to decide.

**Comment by wakemaster39** [comment]
superseded by #1875

**Pull request closed without merging**
