### PR TITLE
WIP - Allow empty repository url if it's already configured

### PR DESCRIPTION
**Pull request by orlevii**
# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

------

I've tested it manually and it works as expected.

How do I write a test for this change?

### CODE REVIEW

**Comment by sinoroc** [comment]
Isn't there something like the repos from `pyproject.toml` are only for fetch (download) and the repos from `poetry config` (`poetry.toml`, etc.) are only for publish (upload)?

**Comment by orlevii** [comment]
@sinoroc What do you mean?

I don't want to specify the repository url in each and every `pyporject.toml`. 

This change allows to configure the repository globally (on the machine) using `poetry config`, and under the `pyporject.toml` specify only the repository name to use.

Is there already a way to do that?

**Comment by sinoroc** [comment]
I agree with you. I believe this is how it should be. I disagree with poetry's design decision to have index URLs in the `pyproject.toml` altogether, as I stated in https://github.com/python-poetry/poetry/issues/3355#issuecomment-726683158. There are some more tickets going in that same direction.

I am just pointing what the current intended behaviour seems to be, as far as I understood it from the following section of the doc for example (and the whole page actually):
* https://python-poetry.org/docs/repositories/#install-dependencies-from-a-private-repository

I could be mistaken of course.

**Comment by orlevii** [comment]
@sinoroc 
Yeah, got your point.
Looks like repositories added with `poetry config` can be only used for publishing purposes.

(just like shown here: https://github.com/python-poetry/poetry/issues/2940#issuecomment-710682131)

It causes some inconsistencies.. Setting credentials with `poetry config http-basic.repo USERNAME PASSWORD` is effecting  both installation and publishing commands.

Anyway, I hope this issue will be addressed soon.

**Comment by Secrus** [comment]
No activity for a long time. Closing

**Pull request closed without merging**
