### PR TITLE
Extract method - Git._folder_args

### PR DESCRIPTION
**Pull request by dazza-codes**
Pure extract-method refactor
- first stage of #1270 
- incremental PR for #1176 
- pure refactor preserves existing behavior, no changes to tests required

## checklist
- doesn't apply here, but adding it for the sake of it
- [x] Added tests for changed code.
- [x] Updated documentation for changed code.

### CODE REVIEW

**Comment by darrenleeweber** [comment]
PRs are moving very slowly, any plans to merge this?
- if PRs like this are not merged quickly, there's a risk they fall behind and need extra attention to rebase them again (and again)

**Comment by darrenleeweber** [comment]
- rebased on latest `develop`
- hope this gets merged soon to keep moving with git-tag feature PRs

**Comment by darrenleeweber** [comment]
Is anyone going to merge this?

**Comment by neersighted** [comment]
Hi! Sorry that this has taken so long to review! Unfortunately, there's been enough churn that this is now totally obsolete. I'm closing this, but if you still want to work on/around this aspect of Poetry you are more than welcome to!

**Pull request closed without merging**
