### PR TITLE
treat collection types in package as immutable

### PR DESCRIPTION
**Pull request by dimbleby**
addresses #8250, #7459: but the interesting part of the fix is in poetry-core and I'll make more comments there

### CODE REVIEW

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry-core/pull/663 is the companion MR and, not for the first time, it will be awkward to find a sequence of merges that keeps both pipelines happy throughout

**Comment by radoering** [comment]
@dimbleby I suppose we have to update poetry-core in this PR to pass mypy. Do you have the time to take care of it?

**Comment by dimbleby** [comment]
gonna need to upgrade poetry core for lots of reasons though, right?  I'd think that wants handling in a separate MR and then this one can simply merge / rebase

either way I wont' be doing anything before the weekend, probably can find time then though.

**Comment by radoering** [comment]
> I'd think that wants handling in a separate MR and then this one can simply merge / rebase

I assumed that mypy would fail after upgrading poetry-core without the changes of this PR but I'll try if it's possible to do it separately or if other things break. (I have the hope that all other things are just deprecation warnings we can address later.)

**Review by radoering — APPROVED** [review]

**Pull request merged**
